//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Sync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SyncResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Sync.SyncResources", typeof(SyncResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting any download in progress....
        /// </summary>
        public static string AbortingAnyDownloadInProgress {
            get {
                return ResourceManager.GetString("AbortingAnyDownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying {0}....
        /// </summary>
        public static string Applying {
            get {
                return ResourceManager.GetString("Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying DB constraint....
        /// </summary>
        public static string ApplyingDBConstraint {
            get {
                return ResourceManager.GetString("ApplyingDBConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes for schema - {0} successfully applied..
        /// </summary>
        public static string ChangesForSchemaSuccessfullyApplied {
            get {
                return ResourceManager.GetString("ChangesForSchemaSuccessfullyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up old data files....
        /// </summary>
        public static string CleaningUpOldDataFiles {
            get {
                return ResourceManager.GetString("CleaningUpOldDataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error: Rebuild an empty database and try again..
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is in corrupted state. Cannot continue file full sync..
        /// </summary>
        public static string DatabaseInCorruptedStateCannotContinueFullSync {
            get {
                return ResourceManager.GetString("DatabaseInCorruptedStateCannotContinueFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying data upgrade....
        /// </summary>
        public static string DataUpgradeRetry {
            get {
                return ResourceManager.GetString("DataUpgradeRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all data....
        /// </summary>
        public static string DeletingAllData {
            get {
                return ResourceManager.GetString("DeletingAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading device level data....
        /// </summary>
        public static string DownloadingDeviceLevelData {
            get {
                return ResourceManager.GetString("DownloadingDeviceLevelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading device level data completed....
        /// </summary>
        public static string DownloadingDeviceLevelDataCompleted {
            get {
                return ResourceManager.GetString("DownloadingDeviceLevelDataCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading facility level data completed....
        /// </summary>
        public static string DownloadingFacilityLevelDataCompleted {
            get {
                return ResourceManager.GetString("DownloadingFacilityLevelDataCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading facility level data files....
        /// </summary>
        public static string DownloadingFacilityLevelDataFiles {
            get {
                return ResourceManager.GetString("DownloadingFacilityLevelDataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading upgraded data....
        /// </summary>
        public static string DownloadingUpgradedData {
            get {
                return ResourceManager.GetString("DownloadingUpgradedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping DB constraint....
        /// </summary>
        public static string DroppingDBConstraint {
            get {
                return ResourceManager.GetString("DroppingDBConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete all data..
        /// </summary>
        public static string FailedToDeleteAllData {
            get {
                return ResourceManager.GetString("FailedToDeleteAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete data. Cannot continue full sync..
        /// </summary>
        public static string FailedToDeleteDataCannotContinueFullSync {
            get {
                return ResourceManager.GetString("FailedToDeleteDataCannotContinueFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download data. Cleaning up any partial data..
        /// </summary>
        public static string FailedToDownloadDataCleaningPartialData {
            get {
                return ResourceManager.GetString("FailedToDownloadDataCleaningPartialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error: Failed to download data from the server. Please retry again..
        /// </summary>
        public static string FailedToDownLoadDataFromServer {
            get {
                return ResourceManager.GetString("FailedToDownLoadDataFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download upgraded data..
        /// </summary>
        public static string FailedToDownloadUpgradedData {
            get {
                return ResourceManager.GetString("FailedToDownloadUpgradedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data or partial files were found at Server. Please try full download at a later time..
        /// </summary>
        public static string FailedToGetDataFileList {
            get {
                return ResourceManager.GetString("FailedToGetDataFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start data upgrade. Please check if all services are running. Press OK to retry..
        /// </summary>
        public static string FailedToStartDataUpgrade {
            get {
                return ResourceManager.GetString("FailedToStartDataUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start full download. Please check if all services are running..
        /// </summary>
        public static string FailedToStartFullDownload {
            get {
                return ResourceManager.GetString("FailedToStartFullDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload pending data. Cannot continue data upgrade..
        /// </summary>
        public static string FailedToUploadPendingDataCannotContinueDataUpgrade {
            get {
                return ResourceManager.GetString("FailedToUploadPendingDataCannotContinueDataUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload pending data. Cannot continue full sync..
        /// </summary>
        public static string FailedToUploadPendingDataCannotContinueFullSync {
            get {
                return ResourceManager.GetString("FailedToUploadPendingDataCannotContinueFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload error: Failed to upload pending data to server. Fix the error and retry again..
        /// </summary>
        public static string FailedToUploadPendingDataToServer {
            get {
                return ResourceManager.GetString("FailedToUploadPendingDataToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} for schema {1} is already downloaded to device. Skipping to download again....
        /// </summary>
        public static string FileForSchemaAlreadyDownloadedToDevice {
            get {
                return ResourceManager.GetString("FileForSchemaAlreadyDownloadedToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device sync service not responding. Please ensure it is running..
        /// </summary>
        public static string FullDownloadCannotAccessSync {
            get {
                return ResourceManager.GetString("FullDownloadCannotAccessSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full download failed: {0}.
        /// </summary>
        public static string FullDownloadFailed {
            get {
                return ResourceManager.GetString("FullDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full download was interrupted, please try again..
        /// </summary>
        public static string FullDownloadInterrupted {
            get {
                return ResourceManager.GetString("FullDownloadInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full download operation will delete existing data from device. Are you sure you want to continue with full download?.
        /// </summary>
        public static string FullDownloadWarning {
            get {
                return ResourceManager.GetString("FullDownloadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid full sync file found at the server. Cannot continue file full sync..
        /// </summary>
        public static string NoValidFullSyncFileFound {
            get {
                return ResourceManager.GetString("NoValidFullSyncFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing facility level data....
        /// </summary>
        public static string ProcessingFacilityLevelData {
            get {
                return ResourceManager.GetString("ProcessingFacilityLevelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all data....
        /// </summary>
        public static string PurgingAllData {
            get {
                return ResourceManager.GetString("PurgingAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-indexing database completed..
        /// </summary>
        public static string ReIndexingDatabaseCompleted {
            get {
                return ResourceManager.GetString("ReIndexingDatabaseCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-indexing database failed..
        /// </summary>
        public static string ReIndexingDatabaseFailed {
            get {
                return ResourceManager.GetString("ReIndexingDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-indexing database started..
        /// </summary>
        public static string ReIndexingDatabaseStarted {
            get {
                return ResourceManager.GetString("ReIndexingDatabaseStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review sync log files for details..
        /// </summary>
        public static string ReviewSyncLogFilesForDetails {
            get {
                return ResourceManager.GetString("ReviewSyncLogFilesForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrinking Database....
        /// </summary>
        public static string ShrinkDatabase {
            get {
                return ResourceManager.GetString("ShrinkDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrinking Database Completed....
        /// </summary>
        public static string ShrinkDatabaseCompleted {
            get {
                return ResourceManager.GetString("ShrinkDatabaseCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping all running tasks....
        /// </summary>
        public static string StoppingAllRunningTasks {
            get {
                return ResourceManager.GetString("StoppingAllRunningTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Maintenance Service....
        /// </summary>
        public static string StoppingMaintenanceService {
            get {
                return ResourceManager.GetString("StoppingMaintenanceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Context or device properties are null in DataUpgrade workflow!.
        /// </summary>
        public static string SyncContextOrDevicePropertiesAreNull {
            get {
                return ResourceManager.GetString("SyncContextOrDevicePropertiesAreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect with server - {0}. Aborting full sync. Please retry again..
        /// </summary>
        public static string UnableToConnectWithServerAbortingFullSync {
            get {
                return ResourceManager.GetString("UnableToConnectWithServerAbortingFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred during full sync. Cleaning up any partial data..
        /// </summary>
        public static string UnknownErrorOccurredCleaningPartialData {
            get {
                return ResourceManager.GetString("UnknownErrorOccurredCleaningPartialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception occurred during data upgrade. Please retry again..
        /// </summary>
        public static string UnknownExceptionOccurredDuringDataUpgrade {
            get {
                return ResourceManager.GetString("UnknownExceptionOccurredDuringDataUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception occurred during full sync. Please retry again..
        /// </summary>
        public static string UnknownExceptionOccurredDuringFullSync {
            get {
                return ResourceManager.GetString("UnknownExceptionOccurredDuringFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating sync statistics....
        /// </summary>
        public static string UpdatingSyncStatistics {
            get {
                return ResourceManager.GetString("UpdatingSyncStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading pending data for data upgrade....
        /// </summary>
        public static string UploadingPendingDataForDataUpgrade {
            get {
                return ResourceManager.GetString("UploadingPendingDataForDataUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for sync services to start..
        /// </summary>
        public static string WaitForSyncService {
            get {
                return ResourceManager.GetString("WaitForSyncService", resourceCulture);
            }
        }
    }
}
