//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Med {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Med.MedResources", typeof(MedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Instructions:.
        /// </summary>
        public static string AdministrationNote {
            get {
                return ResourceManager.GetString("AdministrationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Meds.
        /// </summary>
        public static string AllMeds {
            get {
                return ResourceManager.GetString("AllMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Locations:.
        /// </summary>
        public static string AlternateLocationLbl {
            get {
                return ResourceManager.GetString("AlternateLocationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered amount cannot be greater than 99999.
        /// </summary>
        public static string AmountGreaterthanMax {
            get {
                return ResourceManager.GetString("AmountGreaterthanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name:.
        /// </summary>
        public static string BrandNamelbl {
            get {
                return ResourceManager.GetString("BrandNamelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Med.
        /// </summary>
        public static string CancelMed {
            get {
                return ResourceManager.GetString("CancelMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must complete count before closing drawer or pocket.
        /// </summary>
        public static string CountHardwareCloseAlertText {
            get {
                return ResourceManager.GetString("CountHardwareCloseAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Patient.
        /// </summary>
        public static string CreditPatient {
            get {
                return ResourceManager.GetString("CreditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Now.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string Discontinued {
            get {
                return ResourceManager.GetString("Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispensing Instructions:.
        /// </summary>
        public static string DispensingNote {
            get {
                return ResourceManager.GetString("DispensingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose:.
        /// </summary>
        public static string Doselbl {
            get {
                return ResourceManager.GetString("Doselbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each.
        /// </summary>
        public static string EmptyDosageFormCode {
            get {
                return ResourceManager.GetString("EmptyDosageFormCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Critical Override for Device.
        /// </summary>
        public static string EnableCriticalOverride {
            get {
                return ResourceManager.GetString("EnableCriticalOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Device out of Service.
        /// </summary>
        public static string EnableOutOfService {
            get {
                return ResourceManager.GetString("EnableOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Temporary Non-Profile Mode for Device.
        /// </summary>
        public static string EnableTempNonProfile {
            get {
                return ResourceManager.GetString("EnableTempNonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End: .
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string EndTimelbl {
            get {
                return ResourceManager.GetString("EndTimelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Kits.
        /// </summary>
        public static string FacilityKits {
            get {
                return ResourceManager.GetString("FacilityKits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulary Note:.
        /// </summary>
        public static string FormularyNotelbl {
            get {
                return ResourceManager.GetString("FormularyNotelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency:.
        /// </summary>
        public static string Frequencylbl {
            get {
                return ResourceManager.GetString("Frequencylbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future.
        /// </summary>
        public static string Future {
            get {
                return ResourceManager.GetString("Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Name:.
        /// </summary>
        public static string GenericNamelbl {
            get {
                return ResourceManager.GetString("GenericNamelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater.
        /// </summary>
        public static string Greater {
            get {
                return ResourceManager.GetString("Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kits.
        /// </summary>
        public static string Kits {
            get {
                return ResourceManager.GetString("Kits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24 Hours.
        /// </summary>
        public static string Last24Hours {
            get {
                return ResourceManager.GetString("Last24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Removed.
        /// </summary>
        public static string LastRemoved {
            get {
                return ResourceManager.GetString("LastRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Removed:.
        /// </summary>
        public static string LastRemovedDateLabel {
            get {
                return ResourceManager.GetString("LastRemovedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm MMM dd}.
        /// </summary>
        public static string LastRemovedDateTimeFormat {
            get {
                return ResourceManager.GetString("LastRemovedDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Removed:.
        /// </summary>
        public static string LastRemovedlbl {
            get {
                return ResourceManager.GetString("LastRemovedlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Reason:.
        /// </summary>
        public static string LastRemovedReason {
            get {
                return ResourceManager.GetString("LastRemovedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Last Removed From:.
        /// </summary>
        public static string LastRemovedStationlbl {
            get {
                return ResourceManager.GetString("LastRemovedStationlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm} Today.
        /// </summary>
        public static string LastRemovedTodayTimeFormat {
            get {
                return ResourceManager.GetString("LastRemovedTodayTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By:.
        /// </summary>
        public static string LastRemovedUserBy {
            get {
                return ResourceManager.GetString("LastRemovedUserBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Removed By:.
        /// </summary>
        public static string LastRemovedUserlbl {
            get {
                return ResourceManager.GetString("LastRemovedUserlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Transcations.
        /// </summary>
        public static string LastTranscations {
            get {
                return ResourceManager.GetString("LastTranscations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less.
        /// </summary>
        public static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medications to Waste.
        /// </summary>
        public static string MedicationsToWaste {
            get {
                return ResourceManager.GetString("MedicationsToWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedID:.
        /// </summary>
        public static string MedIDlbl {
            get {
                return ResourceManager.GetString("MedIDlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med Item Header.
        /// </summary>
        public static string MedItemHeader {
            get {
                return ResourceManager.GetString("MedItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string MedNameFormat {
            get {
                return ResourceManager.GetString("MedNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}).
        /// </summary>
        public static string MedProfileTimeRangeFormat {
            get {
                return ResourceManager.GetString("MedProfileTimeRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med Profile.
        /// </summary>
        public static string MedProfileViewTitle {
            get {
                return ResourceManager.GetString("MedProfileViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meds to Waste.
        /// </summary>
        public static string MedsToWaste {
            get {
                return ResourceManager.GetString("MedsToWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Undocumented Wastes.
        /// </summary>
        public static string MyUndocumentedWaste {
            get {
                return ResourceManager.GetString("MyUndocumentedWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name/Dose.
        /// </summary>
        public static string NameDose {
            get {
                return ResourceManager.GetString("NameDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Be Removed After:.
        /// </summary>
        public static string NextRemoveDate {
            get {
                return ResourceManager.GetString("NextRemoveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Profile Meds.
        /// </summary>
        public static string NonProfile {
            get {
                return ResourceManager.GetString("NonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes: .
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Call.
        /// </summary>
        public static string OnCall {
            get {
                return ResourceManager.GetString("OnCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnHold.
        /// </summary>
        public static string OnHold {
            get {
                return ResourceManager.GetString("OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order#.
        /// </summary>
        public static string OrderIDlbl {
            get {
                return ResourceManager.GetString("OrderIDlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string OverrideTaskTitle {
            get {
                return ResourceManager.GetString("OverrideTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Removed.
        /// </summary>
        public static string PastRemoved {
            get {
                return ResourceManager.GetString("PastRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician: .
        /// </summary>
        public static string Physician {
            get {
                return ResourceManager.GetString("Physician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        public static string Prioritylbl {
            get {
                return ResourceManager.GetString("Prioritylbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN.
        /// </summary>
        public static string PRN {
            get {
                return ResourceManager.GetString("PRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN ({0}) / Continuous Infusions ({1}) / On Call ({2}).
        /// </summary>
        public static string PrnHeaderFormat {
            get {
                return ResourceManager.GetString("PrnHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed:.
        /// </summary>
        public static string RemovedLbl {
            get {
                return ResourceManager.GetString("RemovedLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Removelbl {
            get {
                return ResourceManager.GetString("Removelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove List.
        /// </summary>
        public static string RemoveList {
            get {
                return ResourceManager.GetString("RemoveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Med.
        /// </summary>
        public static string RemoveViewTitle {
            get {
                return ResourceManager.GetString("RemoveViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search All Meds to Return.
        /// </summary>
        public static string ReturnAllMeds {
            get {
                return ResourceManager.GetString("ReturnAllMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Removed Meds.
        /// </summary>
        public static string ReturnRemovedMeds {
            get {
                return ResourceManager.GetString("ReturnRemovedMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ReturnViewTitle {
            get {
                return ResourceManager.GetString("ReturnViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route:.
        /// </summary>
        public static string Routelbl {
            get {
                return ResourceManager.GetString("Routelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search All Meds.
        /// </summary>
        public static string SearchAllMeds {
            get {
                return ResourceManager.GetString("SearchAllMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Search box to retrieve matching meds.
        /// </summary>
        public static string SearchAllMedsInstruction {
            get {
                return ResourceManager.GetString("SearchAllMedsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Meds.
        /// </summary>
        public static string SearchMeds {
            get {
                return ResourceManager.GetString("SearchMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Meds.
        /// </summary>
        public static string SecuredMeds {
            get {
                return ResourceManager.GetString("SecuredMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Meds.
        /// </summary>
        public static string SelectedMeds {
            get {
                return ResourceManager.GetString("SelectedMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more medications.
        /// </summary>
        public static string SelectMed {
            get {
                return ResourceManager.GetString("SelectMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Meds.
        /// </summary>
        public static string SelectMeds {
            get {
                return ResourceManager.GetString("SelectMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More History....
        /// </summary>
        public static string ShowMoreHistory {
            get {
                return ResourceManager.GetString("ShowMoreHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: .
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string StartEndDateTimeFormat {
            get {
                return ResourceManager.GetString("StartEndDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string StartTimelbl {
            get {
                return ResourceManager.GetString("StartTimelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAT.
        /// </summary>
        public static string STAT {
            get {
                return ResourceManager.GetString("STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        public static string ToWaste {
            get {
                return ResourceManager.GetString("ToWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Information.
        /// </summary>
        public static string TrackingInformation {
            get {
                return ResourceManager.GetString("TrackingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undocumented Waste.
        /// </summary>
        public static string UndocumentedWaste {
            get {
                return ResourceManager.GetString("UndocumentedWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reason for undocumented waste {0} than expected amount of {1}.
        /// </summary>
        public static string UndocumentedWasteAmountInstruction {
            get {
                return ResourceManager.GetString("UndocumentedWasteAmountInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string UserLbl {
            get {
                return ResourceManager.GetString("UserLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        public static string Waste {
            get {
                return ResourceManager.GetString("Waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search All Meds to Waste.
        /// </summary>
        public static string WasteAllMeds {
            get {
                return ResourceManager.GetString("WasteAllMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Med.
        /// </summary>
        public static string WasteMed {
            get {
                return ResourceManager.GetString("WasteMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Removed Meds.
        /// </summary>
        public static string WasteRemoveTransaction {
            get {
                return ResourceManager.GetString("WasteRemoveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasted without an associated remove transaction.
        /// </summary>
        public static string WasteWithoutRemoveTransaction {
            get {
                return ResourceManager.GetString("WasteWithoutRemoveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string WitnessAnd {
            get {
                return ResourceManager.GetString("WitnessAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness on.
        /// </summary>
        public static string WitnessOn {
            get {
                return ResourceManager.GetString("WitnessOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness on remove .
        /// </summary>
        public static string WitnessOnRemove {
            get {
                return ResourceManager.GetString("WitnessOnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness on remove and waste.
        /// </summary>
        public static string WitnessOnRemoveAndWaste {
            get {
                return ResourceManager.GetString("WitnessOnRemoveAndWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness on.
        /// </summary>
        public static string WitnessOnText {
            get {
                return ResourceManager.GetString("WitnessOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness on waste.
        /// </summary>
        public static string WitnessOnWaste {
            get {
                return ResourceManager.GetString("WitnessOnWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Required.
        /// </summary>
        public static string WitnessRequired {
            get {
                return ResourceManager.GetString("WitnessRequired", resourceCulture);
            }
        }
    }
}
