//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Med {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Med.ReturnResources", typeof(ReturnResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Locations.
        /// </summary>
        public static string AccessibleLocations {
            get {
                return ResourceManager.GetString("AccessibleLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} amount cannot be greater than remaining dispense quantity.
        /// </summary>
        public static string AmountCannotBeGreaterThanDispenseQuantity {
            get {
                return ResourceManager.GetString("AmountCannotBeGreaterThanDispenseQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} amount cannot be empty.
        /// </summary>
        public static string AmountEmpty {
            get {
                return ResourceManager.GetString("AmountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} amount has to be greater than 0.
        /// </summary>
        public static string AmountGreaterThanZero {
            get {
                return ResourceManager.GetString("AmountGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to cancel return of the dispensed medication?.
        /// </summary>
        public static string CancelScanReturnWarning {
            get {
                return ResourceManager.GetString("CancelScanReturnWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Return.
        /// </summary>
        public static string CannotReturn {
            get {
                return ResourceManager.GetString("CannotReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot return a fractional quantity for {0}.
        /// </summary>
        public static string CannotReturnFractionalQuantity {
            get {
                return ResourceManager.GetString("CannotReturnFractionalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot return, waste the scanned medications.
        /// </summary>
        public static string CannotReturnWasteScannedMeds {
            get {
                return ResourceManager.GetString("CannotReturnWasteScannedMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If cannot return, cancel and return to another station or call pharmacy.
        /// </summary>
        public static string ContactPharmacyWarning {
            get {
                return ResourceManager.GetString("ContactPharmacyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date you entered is in the past..
        /// </summary>
        public static string DateEnteredInPast {
            get {
                return ResourceManager.GetString("DateEnteredInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan does not match this medication. Try again..
        /// </summary>
        public static string DoesNotMatchScanIdWarning {
            get {
                return ResourceManager.GetString("DoesNotMatchScanIdWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not return to Stock.
        /// </summary>
        public static string DonotReturnToStock {
            get {
                return ResourceManager.GetString("DonotReturnToStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date cannot be empty.
        /// </summary>
        public static string ExpirationDateEmpty {
            get {
                return ResourceManager.GetString("ExpirationDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Medication Warning.
        /// </summary>
        public static string ExpiredMedicationsWarnigTitle {
            get {
                return ResourceManager.GetString("ExpiredMedicationsWarnigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not return to the pocket. \n\r Close drawer and return to Internal Return Bin..
        /// </summary>
        public static string ExpiredMedWarning {
            get {
                return ResourceManager.GetString("ExpiredMedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External bin.
        /// </summary>
        public static string ExternalBin {
            get {
                return ResourceManager.GetString("ExternalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return amount will exceed the Physical Max of the pocket..
        /// </summary>
        public static string GreaterThanPhysicalMaxWarning {
            get {
                return ResourceManager.GetString("GreaterThanPhysicalMaxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Quantity..
        /// </summary>
        public static string InsufficientQuantity {
            get {
                return ResourceManager.GetString("InsufficientQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal bin.
        /// </summary>
        public static string InternalBin {
            get {
                return ResourceManager.GetString("InternalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this correct?.
        /// </summary>
        public static string IsThisCorrect {
            get {
                return ResourceManager.GetString("IsThisCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot number cannot be empty.
        /// </summary>
        public static string LotIdEmpty {
            get {
                return ResourceManager.GetString("LotIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication to Return.
        /// </summary>
        public static string MedicationToReturn {
            get {
                return ResourceManager.GetString("MedicationToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meds to Return.
        /// </summary>
        public static string MedsToReturn {
            get {
                return ResourceManager.GetString("MedsToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be returned, dispose per hospital policy.
        /// </summary>
        public static string NotReturnable {
            get {
                return ResourceManager.GetString("NotReturnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be returned, waste item.
        /// </summary>
        public static string NotReturnableWaste {
            get {
                return ResourceManager.GetString("NotReturnableWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to override scanning of the dispensed medication?.
        /// </summary>
        public static string OverrideScanWarning {
            get {
                return ResourceManager.GetString("OverrideScanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed:.
        /// </summary>
        public static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Witness.
        /// </summary>
        public static string RequiresWitness {
            get {
                return ResourceManager.GetString("RequiresWitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return bin.
        /// </summary>
        public static string ReturnBin {
            get {
                return ResourceManager.GetString("ReturnBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned without an associated remove transaction.
        /// </summary>
        public static string ReturnedWithoutRemoveTransaction {
            get {
                return ResourceManager.GetString("ReturnedWithoutRemoveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Med.
        /// </summary>
        public static string ReturnMed {
            get {
                return ResourceManager.GetString("ReturnMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan each medication being returned.
        /// </summary>
        public static string ReturnScanInstructionText {
            get {
                return ResourceManager.GetString("ReturnScanInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return scanned medications to the External Return Bin.
        /// </summary>
        public static string ReturnScanMedsToExternalBin {
            get {
                return ResourceManager.GetString("ReturnScanMedsToExternalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return scanned medications to the Internal Return Bin.
        /// </summary>
        public static string ReturnScanMedsToInternalBin {
            get {
                return ResourceManager.GetString("ReturnScanMedsToInternalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return scanned medications to the Pharmacy.
        /// </summary>
        public static string ReturnScanMedsToPharmacy {
            get {
                return ResourceManager.GetString("ReturnScanMedsToPharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ReturnTitle {
            get {
                return ResourceManager.GetString("ReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to External Bin.
        /// </summary>
        public static string ReturnToExternalBin {
            get {
                return ResourceManager.GetString("ReturnToExternalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Internal Bin.
        /// </summary>
        public static string ReturnToInternalBin {
            get {
                return ResourceManager.GetString("ReturnToInternalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Pharmacy.
        /// </summary>
        public static string ReturnToPharmacy {
            get {
                return ResourceManager.GetString("ReturnToPharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Stock.
        /// </summary>
        public static string ReturnToStock {
            get {
                return ResourceManager.GetString("ReturnToStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Item to Return.
        /// </summary>
        public static string ScanItemToReturn {
            get {
                return ResourceManager.GetString("ScanItemToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Item to Return (#{0}).
        /// </summary>
        public static string ScanItemToReturnInstruction {
            get {
                return ResourceManager.GetString("ScanItemToReturnInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Medication.
        /// </summary>
        public static string ScanMedication {
            get {
                return ResourceManager.GetString("ScanMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}.
        /// </summary>
        public static string ScanStatusFormat {
            get {
                return ResourceManager.GetString("ScanStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number cannot be empty.
        /// </summary>
        public static string SerialIdEmpty {
            get {
                return ResourceManager.GetString("SerialIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Max of the pocket will be exceeded..
        /// </summary>
        public static string TotalGreaterThanPhysicalMaxWarning {
            get {
                return ResourceManager.GetString("TotalGreaterThanPhysicalMaxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeds physical max.
        /// </summary>
        public static string TotalGreathanMaxHeader {
            get {
                return ResourceManager.GetString("TotalGreathanMaxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If cannot return, cancel and return to another station or waste.
        /// </summary>
        public static string WasteAndCredit {
            get {
                return ResourceManager.GetString("WasteAndCredit", resourceCulture);
            }
        }
    }
}
