//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Anesthesia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManageMapResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageMapResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Anesthesia.ManageMapResources", typeof(ManageMapResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t assign to pocket that is already pended.
        /// </summary>
        public static string CantAssignToPendedPocket {
            get {
                return ResourceManager.GetString("CantAssignToPendedPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t unload a pocket that is pended.
        /// </summary>
        public static string CantUnloadPendedPocket {
            get {
                return ResourceManager.GetString("CantUnloadPendedPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Move.
        /// </summary>
        public static string ConfirmMove {
            get {
                return ResourceManager.GetString("ConfirmMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Unassign.
        /// </summary>
        public static string ConfirmUnassign {
            get {
                return ResourceManager.GetString("ConfirmUnassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be sure to physically move the medication.  Do you want to continue with the move?.
        /// </summary>
        public static string ContinueWithMovePrompt {
            get {
                return ResourceManager.GetString("ContinueWithMovePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t count a pended item.
        /// </summary>
        public static string CountPendedItemError {
            get {
                return ResourceManager.GetString("CountPendedItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destock.
        /// </summary>
        public static string Destock {
            get {
                return ResourceManager.GetString("Destock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer is failed.
        /// </summary>
        public static string DrawerFailure {
            get {
                return ResourceManager.GetString("DrawerFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer must be opened.
        /// </summary>
        public static string DrawerMustBeOpened {
            get {
                return ResourceManager.GetString("DrawerMustBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the move operation.
        /// </summary>
        public static string MoveOperationInProgress {
            get {
                return ResourceManager.GetString("MoveOperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving:.
        /// </summary>
        public static string Moving {
            get {
                return ResourceManager.GetString("Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind count required - touch and hold the item to count..
        /// </summary>
        public static string MustDemandCount {
            get {
                return ResourceManager.GetString("MustDemandCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform that action.
        /// </summary>
        public static string NoActionPermission {
            get {
                return ResourceManager.GetString("NoActionPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no loaded items.
        /// </summary>
        public static string NoLoadedMeds {
            get {
                return ResourceManager.GetString("NoLoadedMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to load.
        /// </summary>
        public static string NoLoadPermission {
            get {
                return ResourceManager.GetString("NoLoadPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to move.
        /// </summary>
        public static string NoMovePermission {
            get {
                return ResourceManager.GetString("NoMovePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to open the drawer.
        /// </summary>
        public static string NoOpenDrawerPermission {
            get {
                return ResourceManager.GetString("NoOpenDrawerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pended items.
        /// </summary>
        public static string NoPendedMeds {
            get {
                return ResourceManager.GetString("NoPendedMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to unload.
        /// </summary>
        public static string NoUnloadPermission {
            get {
                return ResourceManager.GetString("NoUnloadPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdate tracking is not enabled for this item.
        /// </summary>
        public static string OutdateNotTracking {
            get {
                return ResourceManager.GetString("OutdateNotTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket {0}.
        /// </summary>
        public static string Pocket {
            get {
                return ResourceManager.GetString("Pocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket already moving.
        /// </summary>
        public static string PocketAlreadyMoving {
            get {
                return ResourceManager.GetString("PocketAlreadyMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan the med.
        /// </summary>
        public static string ScanMed {
            get {
                return ResourceManager.GetString("ScanMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Medication.
        /// </summary>
        public static string ScanMedication {
            get {
                return ResourceManager.GetString("ScanMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please secure drawer.
        /// </summary>
        public static string SecureDrawer {
            get {
                return ResourceManager.GetString("SecureDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign.
        /// </summary>
        public static string Unassign {
            get {
                return ResourceManager.GetString("Unassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unassign?.
        /// </summary>
        public static string UnassignConfirmation {
            get {
                return ResourceManager.GetString("UnassignConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload.
        /// </summary>
        public static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
    }
}
