//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Anesthesia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyItemsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyItemsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Anesthesia.MyItemsResources", typeof(MyItemsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items could not be transferred, user does not have permission.
        /// </summary>
        public static string AllItemsNotTransferred {
            get {
                return ResourceManager.GetString("AllItemsNotTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Dosage form cannot be fractional.
        /// </summary>
        public static string DosageFormCannotBeFractional {
            get {
                return ResourceManager.GetString("DosageFormCannotBeFractional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Dosage form cannot be empty.
        /// </summary>
        public static string DosageFormEmptyError {
            get {
                return ResourceManager.GetString("DosageFormEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Enter a value greater than 0.
        /// </summary>
        public static string GreaterThanZeroError {
            get {
                return ResourceManager.GetString("GreaterThanZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Amount.
        /// </summary>
        public static string IssueAmountColumnHeader {
            get {
                return ResourceManager.GetString("IssueAmountColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Cannot be issued, insufficient remaining amount.
        /// </summary>
        public static string IssueInsufficientAmountError {
            get {
                return ResourceManager.GetString("IssueInsufficientAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Meds.
        /// </summary>
        public static string IssueMeds {
            get {
                return ResourceManager.GetString("IssueMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Unable to issue more than the removed amount.
        /// </summary>
        public static string IssueMoreRemoveAmountError {
            get {
                return ResourceManager.GetString("IssueMoreRemoveAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be issued, you do not have permission.
        /// </summary>
        public static string IssueNoPermissionError {
            get {
                return ResourceManager.GetString("IssueNoPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue to Patient.
        /// </summary>
        public static string IssueToPatient {
            get {
                return ResourceManager.GetString("IssueToPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Items.
        /// </summary>
        public static string MyItems {
            get {
                return ResourceManager.GetString("MyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have My Items permission..
        /// </summary>
        public static string NoMyItemsPermission {
            get {
                return ResourceManager.GetString("NoMyItemsPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-controlled Meds.
        /// </summary>
        public static string NonControlledMeds {
            get {
                return ResourceManager.GetString("NonControlledMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength cannot be empty.
        /// </summary>
        public static string StrengthCannotBeEmpty {
            get {
                return ResourceManager.GetString("StrengthCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Amount.
        /// </summary>
        public static string TransferAmount {
            get {
                return ResourceManager.GetString("TransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please have the receiving user enter their credentials.
        /// </summary>
        public static string TransferAuthenticateTitle {
            get {
                return ResourceManager.GetString("TransferAuthenticateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Cannot be transferred, insufficient remaining amount.
        /// </summary>
        public static string TransferInsufficientAmountError {
            get {
                return ResourceManager.GetString("TransferInsufficientAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Unable to transfer more than the removed amount.
        /// </summary>
        public static string TransferMoreRemoveAmountError {
            get {
                return ResourceManager.GetString("TransferMoreRemoveAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be transferred, you do not have permission.
        /// </summary>
        public static string TransferNoPermissionError {
            get {
                return ResourceManager.GetString("TransferNoPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to User.
        /// </summary>
        public static string TransferToUser {
            get {
                return ResourceManager.GetString("TransferToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved My Items.
        /// </summary>
        public static string UnresolvedMyItems {
            get {
                return ResourceManager.GetString("UnresolvedMyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have My Items that have not been resolved. Would you like to resolve them?.
        /// </summary>
        public static string UnresolvedMyItemsQuestion {
            get {
                return ResourceManager.GetString("UnresolvedMyItemsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Items For: {0}.
        /// </summary>
        public static string UserLabel {
            get {
                return ResourceManager.GetString("UserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume cannot be empty.
        /// </summary>
        public static string VolumeCannotBeEmpty {
            get {
                return ResourceManager.GetString("VolumeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        public static string Waste {
            get {
                return ResourceManager.GetString("Waste", resourceCulture);
            }
        }
    }
}
