//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Anesthesia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyKitsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyKitsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Anesthesia.MyKitsResources", typeof(MyKitsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Meds.
        /// </summary>
        public static string AllMeds {
            get {
                return ResourceManager.GetString("AllMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity cannot be empty for {0}.
        /// </summary>
        public static string EmptyQuantity {
            get {
                return ResourceManager.GetString("EmptyQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least 3 letters in the search box to retrieve available meds.
        /// </summary>
        public static string InitialInstructions {
            get {
                return ResourceManager.GetString("InitialInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items are not available at this facility.
        /// </summary>
        public static string ItemsAreNotAvailable {
            get {
                return ResourceManager.GetString("ItemsAreNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit Name.
        /// </summary>
        public static string KitName {
            get {
                return ResourceManager.GetString("KitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit name is required.
        /// </summary>
        public static string KitNameRequired {
            get {
                return ResourceManager.GetString("KitNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Kit Name.
        /// </summary>
        public static string KitNameWatermark {
            get {
                return ResourceManager.GetString("KitNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kits.
        /// </summary>
        public static string Kits {
            get {
                return ResourceManager.GetString("Kits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kit must be selected.
        /// </summary>
        public static string MustSelectKit {
            get {
                return ResourceManager.GetString("MustSelectKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items are associated with this kit.
        /// </summary>
        public static string NoItemsInKit {
            get {
                return ResourceManager.GetString("NoItemsInKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity cannot be greater than {0} for {1}.
        /// </summary>
        public static string QuantityGreaterThanMax {
            get {
                return ResourceManager.GetString("QuantityGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string RequiredFieldIndicator {
            get {
                return ResourceManager.GetString("RequiredFieldIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Med Name.
        /// </summary>
        public static string SelectedMedName {
            get {
                return ResourceManager.GetString("SelectedMedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity cannot be zero for {0}.
        /// </summary>
        public static string ZeroQuantity {
            get {
                return ResourceManager.GetString("ZeroQuantity", resourceCulture);
            }
        }
    }
}
