//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept &amp; Print.
        /// </summary>
        public static string AcceptAndPrint {
            get {
                return ResourceManager.GetString("AcceptAndPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The power was switched off.  Stand by for station shutdown.  Please close all open drawers and doors immediately..
        /// </summary>
        public static string ACPowerFailureByOnOffSwitch {
            get {
                return ResourceManager.GetString("ACPowerFailureByOnOffSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Power has failed.  Please close all open drawers and doors immediately..
        /// </summary>
        public static string ACPowerShutdown {
            get {
                return ResourceManager.GetString("ACPowerShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} d.
        /// </summary>
        public static string AgeInDays {
            get {
                return ResourceManager.GetString("AgeInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} h.
        /// </summary>
        public static string AgeInHours {
            get {
                return ResourceManager.GetString("AgeInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} m.
        /// </summary>
        public static string AgeInMinutes {
            get {
                return ResourceManager.GetString("AgeInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} m.
        /// </summary>
        public static string AgeInMonths {
            get {
                return ResourceManager.GetString("AgeInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} y.
        /// </summary>
        public static string AgeInYears {
            get {
                return ResourceManager.GetString("AgeInYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} y {1} m.
        /// </summary>
        public static string AgeInYearsAndMonths {
            get {
                return ResourceManager.GetString("AgeInYearsAndMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Drawer/Door.
        /// </summary>
        public static string AmbiguousDevice {
            get {
                return ResourceManager.GetString("AmbiguousDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached Printers.
        /// </summary>
        public static string AttachedPrinters {
            get {
                return ResourceManager.GetString("AttachedPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditing Hardware.
        /// </summary>
        public static string AuditingHardware {
            get {
                return ResourceManager.GetString("AuditingHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By:.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Calendar_Accept {
            get {
                return ResourceManager.GetString("Calendar_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Calendar_Clear {
            get {
                return ResourceManager.GetString("Calendar_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Calendar_Today {
            get {
                return ResourceManager.GetString("Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonTitle {
            get {
                return ResourceManager.GetString("CancelButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All.
        /// </summary>
        public static string CancelRemaining {
            get {
                return ResourceManager.GetString("CancelRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot access the contents without recovering.
        /// </summary>
        public static string CannotAccessUnlessRecovered {
            get {
                return ResourceManager.GetString("CannotAccessUnlessRecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Continue.
        /// </summary>
        public static string CantContinue {
            get {
                return ResourceManager.GetString("CantContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is on..
        /// </summary>
        public static string CapsWarningText {
            get {
                return ResourceManager.GetString("CapsWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the window to continue.
        /// </summary>
        public static string ClickToContinue {
            get {
                return ResourceManager.GetString("ClickToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Window to Begin.
        /// </summary>
        public static string ClickWindowToBegin {
            get {
                return ResourceManager.GetString("ClickWindowToBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all open hardware.
        /// </summary>
        public static string CloseAllOpenHardware {
            get {
                return ResourceManager.GetString("CloseAllOpenHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Cubie Lid Now.
        /// </summary>
        public static string CloseCubieLidMsg {
            get {
                return ResourceManager.GetString("CloseCubieLidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Door Now.
        /// </summary>
        public static string CloseDoorMsg {
            get {
                return ResourceManager.GetString("CloseDoorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Drawer Now.
        /// </summary>
        public static string CloseDrawerMsg {
            get {
                return ResourceManager.GetString("CloseDrawerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Hardware.
        /// </summary>
        public static string CloseHardware {
            get {
                return ResourceManager.GetString("CloseHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close open hardware.
        /// </summary>
        public static string CloseOpenHardware {
            get {
                return ResourceManager.GetString("CloseOpenHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medications cannot be accessed until the failed storage space is recovered..
        /// </summary>
        public static string CloseOpenHardwareWarning {
            get {
                return ResourceManager.GetString("CloseOpenHardwareWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaVinci.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Items: {0}.
        /// </summary>
        public static string CompletedScanItemsTextFormat {
            get {
                return ResourceManager.GetString("CompletedScanItemsTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed items: {0} of {1}.
        /// </summary>
        public static string CompletedScanItemsWithTotalTextFormat {
            get {
                return ResourceManager.GetString("CompletedScanItemsWithTotalTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to Fail {0}.
        /// </summary>
        public static string ConfirmFailHardwareCommandTitle {
            get {
                return ResourceManager.GetString("ConfirmFailHardwareCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing Confirm will fail the {0}.
        /// </summary>
        public static string ConfirmHardwareFail {
            get {
                return ResourceManager.GetString("ConfirmHardwareFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2024 BD. All rights reserved. Unless otherwise noted, BD, the BD Logo and all other trademarks are property of Becton, Dickinson and Company. Covered by one or more of the following: Patents, Brevets, Patentes, Patenten, Patente, Brevetti, US 6,269,340; CA 2, 125, 693; DE 69329774; OK 0649316; ES 2154651; JP 7,502,678, SG 49695; US 5,681, 285, Other patents pending..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} BD. All rights reserved. Unless otherwise noted, BD, the BD Logo and all other trademarks are property of Becton, Dickinson and Company..
        /// </summary>
        public static string CopyrightShort {
            get {
                return ResourceManager.GetString("CopyrightShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count cannot be empty.
        /// </summary>
        public static string CountCannotBeEmpty {
            get {
                return ResourceManager.GetString("CountCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count cannot be greater than {0}.
        /// </summary>
        public static string CountCannotBeGreaterThanMax {
            get {
                return ResourceManager.GetString("CountCannotBeGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count cannot be less than {0}.
        /// </summary>
        public static string CountCannotBeLessThan {
            get {
                return ResourceManager.GetString("CountCannotBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Override.
        /// </summary>
        public static string CriticalOverride {
            get {
                return ResourceManager.GetString("CriticalOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubie lid.
        /// </summary>
        public static string CubieLid {
            get {
                return ResourceManager.GetString("CubieLid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubie Lid Failed.
        /// </summary>
        public static string CubieLidFailure {
            get {
                return ResourceManager.GetString("CubieLidFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on CUBIE lid and/or press &quot;Retry&quot;.
        /// </summary>
        public static string CubieRetryInstruction {
            get {
                return ResourceManager.GetString("CubieRetryInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Drawer.
        /// </summary>
        public static string CurrentDrawer {
            get {
                return ResourceManager.GetString("CurrentDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMddyyyy.
        /// </summary>
        public static string DateControlLongParseFormat {
            get {
                return ResourceManager.GetString("DateControlLongParseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMddyy.
        /// </summary>
        public static string DateControlShortParseFormat {
            get {
                return ResourceManager.GetString("DateControlShortParseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMDDYYYY.
        /// </summary>
        public static string DateControlWatermark {
            get {
                return ResourceManager.GetString("DateControlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMM dd, yyyy}.
        /// </summary>
        public static string DateFormatXAML {
            get {
                return ResourceManager.GetString("DateFormatXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM yyyy.
        /// </summary>
        public static string DateOfBirthMonthPrecisionFormat {
            get {
                return ResourceManager.GetString("DateOfBirthMonthPrecisionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy.
        /// </summary>
        public static string DateOfBirthYearPrecisionFormat {
            get {
                return ResourceManager.GetString("DateOfBirthYearPrecisionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DateOutOfRangeCaption {
            get {
                return ResourceManager.GetString("DateOutOfRangeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected date is outside of the available range.
        /// </summary>
        public static string DateOutOfRangeMessage {
            get {
                return ResourceManager.GetString("DateOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMM} {1:dd}-{2:dd}, {3:yyyy}.
        /// </summary>
        public static string DateRangeFormat1 {
            get {
                return ResourceManager.GetString("DateRangeFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMM} {1:dd} - {2:MMM} {3:dd}, {4:yyyy}.
        /// </summary>
        public static string DateRangeFormat2 {
            get {
                return ResourceManager.GetString("DateRangeFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMM} {1:dd}, {2:yyyy} - {3:MMM} {4:dd}, {5:yyyy}.
        /// </summary>
        public static string DateRangeFormat3 {
            get {
                return ResourceManager.GetString("DateRangeFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DateSelectionControlsDay {
            get {
                return ResourceManager.GetString("DateSelectionControlsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string DateSelectionControlsDayPattern {
            get {
                return ResourceManager.GetString("DateSelectionControlsDayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string DateSelectionControlsMonth {
            get {
                return ResourceManager.GetString("DateSelectionControlsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        public static string DateSelectionControlsMonthPattern {
            get {
                return ResourceManager.GetString("DateSelectionControlsMonthPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M,D,Y.
        /// </summary>
        public static string DateSelectionControlsPosition {
            get {
                return ResourceManager.GetString("DateSelectionControlsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string DateSelectionControlsYear {
            get {
                return ResourceManager.GetString("DateSelectionControlsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YY or YYYY.
        /// </summary>
        public static string DateSelectionControlsYearPattern {
            get {
                return ResourceManager.GetString("DateSelectionControlsYearPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMM dd, yyyy HH:mm}.
        /// </summary>
        public static string DateTimeFormatXAML {
            get {
                return ResourceManager.GetString("DateTimeFormatXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFROST MODE.
        /// </summary>
        public static string DefrostMode {
            get {
                return ResourceManager.GetString("DefrostMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Count.
        /// </summary>
        public static string DemandCount {
            get {
                return ResourceManager.GetString("DemandCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Printers.
        /// </summary>
        public static string DevicePrinters {
            get {
                return ResourceManager.GetString("DevicePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeviceRecoveryCancelText {
            get {
                return ResourceManager.GetString("DeviceRecoveryCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string DeviceRecoveryStartText {
            get {
                return ResourceManager.GetString("DeviceRecoveryStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Printer.
        /// </summary>
        public static string DeviceThermalPrinter {
            get {
                return ResourceManager.GetString("DeviceThermalPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected Mode.
        /// </summary>
        public static string DiconnectedMode {
            get {
                return ResourceManager.GetString("DiconnectedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancies.
        /// </summary>
        public static string DiscrepanciesLegend {
            get {
                return ResourceManager.GetString("DiscrepanciesLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept &amp; Back.
        /// </summary>
        public static string DiscrepancyAcceptAndBackText {
            get {
                return ResourceManager.GetString("DiscrepancyAcceptAndBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string DiscrepancyAcceptText {
            get {
                return ResourceManager.GetString("DiscrepancyAcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note:.
        /// </summary>
        public static string DiscrepancyAddNoteText {
            get {
                return ResourceManager.GetString("DiscrepancyAddNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string DiscrepancyBackText {
            get {
                return ResourceManager.GetString("DiscrepancyBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DiscrepancyCancelText {
            get {
                return ResourceManager.GetString("DiscrepancyCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note text cannot be blank.
        /// </summary>
        public static string DiscrepancyCannotAddBlankNoteError {
            get {
                return ResourceManager.GetString("DiscrepancyCannotAddBlankNoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must choose a resolution reason.
        /// </summary>
        public static string DiscrepancyChooseResolutionError {
            get {
                return ResourceManager.GetString("DiscrepancyChooseResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string DiscrepancyCountText {
            get {
                return ResourceManager.GetString("DiscrepancyCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DiscrepancyNextText {
            get {
                return ResourceManager.GetString("DiscrepancyNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to count this item.
        /// </summary>
        public static string DiscrepancyNotCountPermissionText {
            get {
                return ResourceManager.GetString("DiscrepancyNotCountPermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Permissions.
        /// </summary>
        public static string DiscrepancyNotCountPermissionTitle {
            get {
                return ResourceManager.GetString("DiscrepancyNotCountPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DiscrepancyNotesText {
            get {
                return ResourceManager.GetString("DiscrepancyNotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string DiscrepancyResolveText {
            get {
                return ResourceManager.GetString("DiscrepancyResolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string DiscrepancyStartText {
            get {
                return ResourceManager.GetString("DiscrepancyStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancies.
        /// </summary>
        public static string DiscrepancyTaskName {
            get {
                return ResourceManager.GetString("DiscrepancyTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to door.
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drawer.
        /// </summary>
        public static string Drawer {
            get {
                return ResourceManager.GetString("Drawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject Filtered.
        /// </summary>
        public static string EjectFiltered {
            get {
                return ResourceManager.GetString("EjectFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject Selected.
        /// </summary>
        public static string EjectSelected {
            get {
                return ResourceManager.GetString("EjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Return Bin.
        /// </summary>
        public static string EmptyReturnBin {
            get {
                return ResourceManager.GetString("EmptyReturnBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press accept to continue.
        /// </summary>
        public static string ErrorAcceptMsg {
            get {
                return ResourceManager.GetString("ErrorAcceptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorNotification {
            get {
                return ResourceManager.GetString("ErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubie failure.
        /// </summary>
        public static string ErrorOpenCubie {
            get {
                return ResourceManager.GetString("ErrorOpenCubie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door failure.
        /// </summary>
        public static string ErrorOpenDoor {
            get {
                return ResourceManager.GetString("ErrorOpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer failure.
        /// </summary>
        public static string ErrorOpenDrawer {
            get {
                return ResourceManager.GetString("ErrorOpenDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired medications.
        /// </summary>
        public static string ExpiredMedications {
            get {
                return ResourceManager.GetString("ExpiredMedications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hardware.
        /// </summary>
        public static string ExposeStorageSpace {
            get {
                return ResourceManager.GetString("ExposeStorageSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Printers.
        /// </summary>
        public static string ExternalPrinters {
            get {
                return ResourceManager.GetString("ExternalPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Hardware.
        /// </summary>
        public static string FailedHardwareLegend {
            get {
                return ResourceManager.GetString("FailedHardwareLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to open.
        /// </summary>
        public static string FailedToOpen {
            get {
                return ResourceManager.GetString("FailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you press &quot;Confirm&quot;, no one will be able to remove meds from this {0} until it is recovered.
        /// </summary>
        public static string FailFinalInstruction {
            get {
                return ResourceManager.GetString("FailFinalInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Hardware.
        /// </summary>
        public static string FailHardware {
            get {
                return ResourceManager.GetString("FailHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it still does not open, check &quot;Can&apos;t Continue&quot;.
        /// </summary>
        public static string FailInstruction {
            get {
                return ResourceManager.GetString("FailInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Lid.
        /// </summary>
        public static string FailLid {
            get {
                return ResourceManager.GetString("FailLid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Storage Bin.
        /// </summary>
        public static string FailRefrigeratorBin {
            get {
                return ResourceManager.GetString("FailRefrigeratorBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Sync Required.
        /// </summary>
        public static string FullSyncRequired {
            get {
                return ResourceManager.GetString("FullSyncRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Search.
        /// </summary>
        public static string GlobalSearch {
            get {
                return ResourceManager.GetString("GlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required hardware resources are already in use by another user or application.
        /// </summary>
        public static string HardwareResourcesBusy {
            get {
                return ResourceManager.GetString("HardwareResourcesBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeButtonTitle {
            get {
                return ResourceManager.GetString("HomeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Conversion is in Progress....
        /// </summary>
        public static string HostConversionInProgress {
            get {
                return ResourceManager.GetString("HostConversionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this message persists after attempting to close, select “Can’t Continue” and confirm.
        /// </summary>
        public static string IfUnableToCloseFailHardware {
            get {
                return ResourceManager.GetString("IfUnableToCloseFailHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        public static string InfoCaption {
            get {
                return ResourceManager.GetString("InfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationNotification {
            get {
                return ResourceManager.GetString("InformationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Application.
        /// </summary>
        public static string InitializingApplication {
            get {
                return ResourceManager.GetString("InitializingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Device Manager.
        /// </summary>
        public static string InitializingDeviceManager {
            get {
                return ResourceManager.GetString("InitializingDeviceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Peripherals.
        /// </summary>
        public static string InitializingPeripherals {
            get {
                return ResourceManager.GetString("InitializingPeripherals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing System Bus.
        /// </summary>
        public static string InitializingSystemBus {
            get {
                return ResourceManager.GetString("InitializingSystemBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient orders may not be current: Order Interface problem for {0}h {1}m.
        /// </summary>
        public static string InterfaceDownOrderTooltip {
            get {
                return ResourceManager.GetString("InterfaceDownOrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient orders may not be current: Order Interface problem for {0}m.
        /// </summary>
        public static string InterfaceDownOrderTooltipZeroHours {
            get {
                return ResourceManager.GetString("InterfaceDownOrderTooltipZeroHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient data may not be current: Patient Interface problem for {0}h {1}m.
        /// </summary>
        public static string InterfaceDownPatientTooltip {
            get {
                return ResourceManager.GetString("InterfaceDownPatientTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient data may not be current: Patient Interface problem for {0}m.
        /// </summary>
        public static string InterfaceDownPatientTooltipZeroHours {
            get {
                return ResourceManager.GetString("InterfaceDownPatientTooltipZeroHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Return Bin.
        /// </summary>
        public static string InternalReturnBinHeader {
            get {
                return ResourceManager.GetString("InternalReturnBinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active ?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired ?.
        /// </summary>
        public static string IsExpired {
            get {
                return ResourceManager.GetString("IsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked ?.
        /// </summary>
        public static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        public static string LabelPrinter {
            get {
                return ResourceManager.GetString("LabelPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string Landing {
            get {
                return ResourceManager.GetString("Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1.
        /// </summary>
        public static string LessThanOne {
            get {
                return ResourceManager.GetString("LessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location {0} of {1}: {2}.
        /// </summary>
        public static string LocationWithCount {
            get {
                return ResourceManager.GetString("LocationWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to be timed out in.
        /// </summary>
        public static string LoggingOut {
            get {
                return ResourceManager.GetString("LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string LoggingOutSeconds {
            get {
                return ResourceManager.GetString("LoggingOutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LoginButtonTitle {
            get {
                return ResourceManager.GetString("LoginButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been terminated.
        /// </summary>
        public static string LogoutWarningMessage {
            get {
                return ResourceManager.GetString("LogoutWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med Class Not Specified.
        /// </summary>
        public static string MedClassNotSpecified {
            get {
                return ResourceManager.GetString("MedClassNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires a minimum 1024 x 768 screen size.
        /// </summary>
        public static string MinimumScreenSize {
            get {
                return ResourceManager.GetString("MinimumScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _More.
        /// </summary>
        public static string MoreMainMenuTitle {
            get {
                return ResourceManager.GetString("MoreMainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string NameValueFormat {
            get {
                return ResourceManager.GetString("NameValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm} - next upgrade(LCR only).
        /// </summary>
        public static string NextUpgradeFormat {
            get {
                return ResourceManager.GetString("NextUpgradeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButtonTitle {
            get {
                return ResourceManager.GetString("NoButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items selected.
        /// </summary>
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no results to display.
        /// </summary>
        public static string NoItemsToDisplay {
            get {
                return ResourceManager.GetString("NoItemsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        public static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Profile.
        /// </summary>
        public static string NonProfileMode {
            get {
                return ResourceManager.GetString("NonProfileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no results to display..
        /// </summary>
        public static string NoSearchResultlbl {
            get {
                return ResourceManager.GetString("NoSearchResultlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all items are displayed.
        /// </summary>
        public static string NotAllItemsDisplayed {
            get {
                return ResourceManager.GetString("NotAllItemsDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available:.
        /// </summary>
        public static string NotAvailableTitle {
            get {
                return ResourceManager.GetString("NotAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonTitle {
            get {
                return ResourceManager.GetString("OkButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream OpenHardware {
            get {
                return ResourceManager.GetStream("OpenHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string OrderNotificationIconLetter {
            get {
                return ResourceManager.GetString("OrderNotificationIconLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Drawers.
        /// </summary>
        public static string OtherDrawers {
            get {
                return ResourceManager.GetString("OtherDrawers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Service.
        /// </summary>
        public static string OutOfService {
            get {
                return ResourceManager.GetString("OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Scan.
        /// </summary>
        public static string OverrideScan {
            get {
                return ResourceManager.GetString("OverrideScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}/{2}.
        /// </summary>
        public static string PatientLocationFormat {
            get {
                return ResourceManager.GetString("PatientLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string PatientLocationFormatWithoutBed {
            get {
                return ResourceManager.GetString("PatientLocationFormatWithoutBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string PatientNotificationIconLetter {
            get {
                return ResourceManager.GetString("PatientNotificationIconLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients and orders may not be current.
        /// </summary>
        public static string PatientsOrdersNotCurrent {
            get {
                return ResourceManager.GetString("PatientsOrdersNotCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open drawer to access.
        /// </summary>
        public static string PleaseExposeStorageSpace {
            get {
                return ResourceManager.GetString("PleaseExposeStorageSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please secure Storage Space:.
        /// </summary>
        public static string PleaseSecureStorageSpace {
            get {
                return ResourceManager.GetString("PleaseSecureStorageSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pocket.
        /// </summary>
        public static string Pocket {
            get {
                return ResourceManager.GetString("Pocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Setup.
        /// </summary>
        public static string PrinterSetup {
            get {
                return ResourceManager.GetString("PrinterSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing in progress..
        /// </summary>
        public static string PrintinginProgress {
            get {
                return ResourceManager.GetString("PrintinginProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Label.
        /// </summary>
        public static string PrintLabel {
            get {
                return ResourceManager.GetString("PrintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Mode.
        /// </summary>
        public static string ProfileMode {
            get {
                return ResourceManager.GetString("ProfileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not answered: {0}.
        /// </summary>
        public static string QuestionNotAnsweredFormat {
            get {
                return ResourceManager.GetString("QuestionNotAnsweredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not answered for {0}: {1}.
        /// </summary>
        public static string QuestionNotAnsweredForMedFormat {
            get {
                return ResourceManager.GetString("QuestionNotAnsweredForMedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued medications.
        /// </summary>
        public static string QueuedMedications {
            get {
                return ResourceManager.GetString("QueuedMedications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrigerator Bin.
        /// </summary>
        public static string RefrigeratorBin {
            get {
                return ResourceManager.GetString("RefrigeratorBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote updates for this station are available.  If you prefer to defer installation press &quot;Install later&quot;, otherwise the system will automatically shutdown..
        /// </summary>
        public static string RemoteUpdateAvailableShutdownMessage {
            get {
                return ResourceManager.GetString("RemoteUpdateAvailableShutdownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Later.
        /// </summary>
        public static string RemoteUpdateDeferInstallButtonText {
            get {
                return ResourceManager.GetString("RemoteUpdateDeferInstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}.
        /// </summary>
        public static string RemovedDetailsTextFormat {
            get {
                return ResourceManager.GetString("RemovedDetailsTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets, Receipts and Reports.
        /// </summary>
        public static string ReportPrinter {
            get {
                return ResourceManager.GetString("ReportPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rx Check needed.
        /// </summary>
        public static string RxCheck {
            get {
                return ResourceManager.GetString("RxCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Medication ({0}).
        /// </summary>
        public static string ScanInstructionFormat {
            get {
                return ResourceManager.GetString("ScanInstructionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan each medication being returned.
        /// </summary>
        public static string ScanInstructionText {
            get {
                return ResourceManager.GetString("ScanInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan  Medication.
        /// </summary>
        public static string ScanMedication {
            get {
                return ResourceManager.GetString("ScanMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please secure all open hardware.
        /// </summary>
        public static string SecureHardwareInstruction {
            get {
                return ResourceManager.GetString("SecureHardwareInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Hardware.
        /// </summary>
        public static string SecureHardwareTitle {
            get {
                return ResourceManager.GetString("SecureHardwareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securing Hardware. Please wait..
        /// </summary>
        public static string SecuringHardware {
            get {
                return ResourceManager.GetString("SecuringHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Drawer.
        /// </summary>
        public static string SelectDrawerTitle {
            get {
                return ResourceManager.GetString("SelectDrawerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Meds.
        /// </summary>
        public static string SelectedMeds {
            get {
                return ResourceManager.GetString("SelectedMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Label Printer.
        /// </summary>
        public static string SelectLabelPrinter {
            get {
                return ResourceManager.GetString("SelectLabelPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a printer.
        /// </summary>
        public static string SelectPrinter {
            get {
                return ResourceManager.GetString("SelectPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Sheet, Receipt and Report Printer.
        /// </summary>
        public static string SelectReportPrinter {
            get {
                return ResourceManager.GetString("SelectReportPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Task to Start.
        /// </summary>
        public static string SelectTaskStart {
            get {
                return ResourceManager.GetString("SelectTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/dd/yyyy.
        /// </summary>
        public static string ShortDateDisplay {
            get {
                return ResourceManager.GetString("ShortDateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy.
        /// </summary>
        public static string ShortDateFormat {
            get {
                return ResourceManager.GetString("ShortDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M/d/yyyy.
        /// </summary>
        public static string ShortDatePatternLiteralForMessages {
            get {
                return ResourceManager.GetString("ShortDatePatternLiteralForMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMdd,yyyy HH:mmtt.
        /// </summary>
        public static string ShortDateTimeAMPMFormat {
            get {
                return ResourceManager.GetString("ShortDateTimeAMPMFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy HH:mm.
        /// </summary>
        public static string ShortDateTimeFormat {
            get {
                return ResourceManager.GetString("ShortDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy HH:mm:ss.
        /// </summary>
        public static string ShortDateTimeSecondsFormat {
            get {
                return ResourceManager.GetString("ShortDateTimeSecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy.
        /// </summary>
        public static string ShortMonthDateFormat {
            get {
                return ResourceManager.GetString("ShortMonthDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string ShortTimeFormat {
            get {
                return ResourceManager.GetString("ShortTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutButtonTitle {
            get {
                return ResourceManager.GetString("SignOutButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Remaining Quantity.
        /// </summary>
        public static string SkipRemainingQuantity {
            get {
                return ResourceManager.GetString("SkipRemainingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Software.
        /// </summary>
        public static string SoftwareUpdateCommand {
            get {
                return ResourceManager.GetString("SoftwareUpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SoftwareUpdateDescription {
            get {
                return ResourceManager.GetString("SoftwareUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est # of minutes to update.
        /// </summary>
        public static string SoftwareUpdateEstMinutesForUpdate {
            get {
                return ResourceManager.GetString("SoftwareUpdateEstMinutesForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SoftwareUpdateName {
            get {
                return ResourceManager.GetString("SoftwareUpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Reboot.
        /// </summary>
        public static string SoftwareUpdateRequiresReboot {
            get {
                return ResourceManager.GetString("SoftwareUpdateRequiresReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Updates Available.
        /// </summary>
        public static string SoftwareUpdatesAvailable {
            get {
                return ResourceManager.GetString("SoftwareUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Updates.
        /// </summary>
        public static string SoftwareUpdatesTitle {
            get {
                return ResourceManager.GetString("SoftwareUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total estimated time to apply software updates: {0} minutes.
        /// </summary>
        public static string SoftwareUpdateTotalEstimatedMinutesMessage {
            get {
                return ResourceManager.GetString("SoftwareUpdateTotalEstimatedMinutesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch screen to begin.
        /// </summary>
        public static string SplashScreenTitle {
            get {
                return ResourceManager.GetString("SplashScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyxis™ Anesthesia Station ES.
        /// </summary>
        public static string SplashStationApplicationTitleAnesthesia {
            get {
                return ResourceManager.GetString("SplashStationApplicationTitleAnesthesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyxis™ CII Safe ES.
        /// </summary>
        public static string SplashStationApplicationTitleGcsm {
            get {
                return ResourceManager.GetString("SplashStationApplicationTitleGcsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyxis™ MedStation™ ES.
        /// </summary>
        public static string SplashStationApplicationTitleMed {
            get {
                return ResourceManager.GetString("SplashStationApplicationTitleMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyxis™ Med Mini ES.
        /// </summary>
        public static string SplashStationApplicationTitleMini {
            get {
                return ResourceManager.GetString("SplashStationApplicationTitleMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyxis™ Anesthesia Station ES.
        /// </summary>
        public static string SplashStationWindowTitleAnesthesia {
            get {
                return ResourceManager.GetString("SplashStationWindowTitleAnesthesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyxis™ Med Mini ES.
        /// </summary>
        public static string SplashStationWindowTitleMini {
            get {
                return ResourceManager.GetString("SplashStationWindowTitleMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD Pyxis™ Anesthesia Station ES.
        /// </summary>
        public static string StationApplicationTitleAnesthesia {
            get {
                return ResourceManager.GetString("StationApplicationTitleAnesthesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD Pyxis™ CII Safe ES.
        /// </summary>
        public static string StationApplicationTitleGcsm {
            get {
                return ResourceManager.GetString("StationApplicationTitleGcsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD Pyxis™ MedStation™ ES.
        /// </summary>
        public static string StationApplicationTitleMed {
            get {
                return ResourceManager.GetString("StationApplicationTitleMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD Pyxis™ Med Mini ES.
        /// </summary>
        public static string StationApplicationTitleMini {
            get {
                return ResourceManager.GetString("StationApplicationTitleMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD Pyxis™ Anesthesia Station ES.
        /// </summary>
        public static string StationWindowTitleAnesthesia {
            get {
                return ResourceManager.GetString("StationWindowTitleAnesthesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD Pyxis™ CII Safe ES.
        /// </summary>
        public static string StationWindowTitleGcsm {
            get {
                return ResourceManager.GetString("StationWindowTitleGcsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD Pyxis™ Med Mini ES.
        /// </summary>
        public static string StationWindowTitleMini {
            get {
                return ResourceManager.GetString("StationWindowTitleMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed.
        /// </summary>
        public static string StorageSpaceFailed {
            get {
                return ResourceManager.GetString("StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not synchronizing: Patients, orders, and dispense transactions may not be up to date..
        /// </summary>
        public static string SyncStopped {
            get {
                return ResourceManager.GetString("SyncStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync upload error - Retrying.
        /// </summary>
        public static string SyncUploadRetry {
            get {
                return ResourceManager.GetString("SyncUploadRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync upload stopped.
        /// </summary>
        public static string SyncUploadStopped {
            get {
                return ResourceManager.GetString("SyncUploadStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SystemAboutTitle {
            get {
                return ResourceManager.GetString("SystemAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string SystemHelpTitle {
            get {
                return ResourceManager.GetString("SystemHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is not detecting that the {0} is closed.
        /// </summary>
        public static string SystemNotDetectingHardware {
            get {
                return ResourceManager.GetString("SystemNotDetectingHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string SystemTutorialTitle {
            get {
                return ResourceManager.GetString("SystemTutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Non-Profile Mode.
        /// </summary>
        public static string TempNonProfileModeLegend {
            get {
                return ResourceManager.GetString("TempNonProfileModeLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string TextDelimiter {
            get {
                return ResourceManager.GetString("TextDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are medications to destock.
        /// </summary>
        public static string ThereAreMedicationsToDestock {
            get {
                return ResourceManager.GetString("ThereAreMedicationsToDestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are medications to unload.
        /// </summary>
        public static string ThereAreMedicationsToUnload {
            get {
                return ResourceManager.GetString("ThereAreMedicationsToUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error accessing Storage Space:.
        /// </summary>
        public static string ThereWasAnError {
            get {
                return ResourceManager.GetString("ThereWasAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm:ss}.
        /// </summary>
        public static string TimeSecondsFormatXAML {
            get {
                return ResourceManager.GetString("TimeSecondsFormatXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Screen to Begin.
        /// </summary>
        public static string TouchScreenToBegin {
            get {
                return ResourceManager.GetString("TouchScreenToBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch the screen to continue.
        /// </summary>
        public static string TouchToContinue {
            get {
                return ResourceManager.GetString("TouchToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tracking information for item {0}.
        /// </summary>
        public static string TrackingInfoInstructionText {
            get {
                return ResourceManager.GetString("TrackingInfoInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Medication.
        /// </summary>
        public static string TrackingInfoRequired {
            get {
                return ResourceManager.GetString("TrackingInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred while recording a transaction, you will be signed out. Sign back in to continue..
        /// </summary>
        public static string TransactionExceptionMessage {
            get {
                return ResourceManager.GetString("TransactionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Scan.
        /// </summary>
        public static string UnableToScan {
            get {
                return ResourceManager.GetString("UnableToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undocumented waste.
        /// </summary>
        public static string UndocumentedWaste {
            get {
                return ResourceManager.GetString("UndocumentedWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnknownErrorCaption {
            get {
                return ResourceManager.GetString("UnknownErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has encountered an unexpected exception.  The information has been logged for diagnostic purposes and you will now be logged out of all areas..
        /// </summary>
        public static string UnknownErrorText {
            get {
                return ResourceManager.GetString("UnknownErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreconciled discrepancies.
        /// </summary>
        public static string UnreconciledDiscrepancies {
            get {
                return ResourceManager.GetString("UnreconciledDiscrepancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Software.
        /// </summary>
        public static string UpdateSoftware {
            get {
                return ResourceManager.GetString("UpdateSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS communication has been lost.  Notify your system administrator immediately..
        /// </summary>
        public static string UpsDisconnectedMessage {
            get {
                return ResourceManager.GetString("UpsDisconnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string UserNameFormat {
            get {
                return ResourceManager.GetString("UserNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningNotification {
            get {
                return ResourceManager.GetString("WarningNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness.
        /// </summary>
        public static string Witness {
            get {
                return ResourceManager.GetString("Witness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witnessed By: {0}.
        /// </summary>
        public static string WitnessBy {
            get {
                return ResourceManager.GetString("WitnessBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Items.
        /// </summary>
        public static string WitnessItems {
            get {
                return ResourceManager.GetString("WitnessItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Password.
        /// </summary>
        public static string WitnessPassword {
            get {
                return ResourceManager.GetString("WitnessPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness this!.
        /// </summary>
        public static string WitnessThis {
            get {
                return ResourceManager.GetString("WitnessThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Username.
        /// </summary>
        public static string WitnessUsername {
            get {
                return ResourceManager.GetString("WitnessUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButtonTitle {
            get {
                return ResourceManager.GetString("YesButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have undocumented waste.
        /// </summary>
        public static string YouHaveUndocumentedWaste {
            get {
                return ResourceManager.GetString("YouHaveUndocumentedWaste", resourceCulture);
            }
        }
    }
}
