//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DrawerConfigurationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DrawerConfigurationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Common.DrawerConfigurationResources", typeof(DrawerConfigurationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cabinet - 6 Drawers.
        /// </summary>
        public static string Add6Drawer {
            get {
                return ResourceManager.GetString("Add6Drawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cabinet - 7 Drawers.
        /// </summary>
        public static string Add7Drawer {
            get {
                return ResourceManager.GetString("Add7Drawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cabinet.
        /// </summary>
        public static string AddCabinet {
            get {
                return ResourceManager.GetString("AddCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add External Bin.
        /// </summary>
        public static string AddExternalBin {
            get {
                return ResourceManager.GetString("AddExternalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add External Return Bin.
        /// </summary>
        public static string AddExternalReturnBin {
            get {
                return ResourceManager.GetString("AddExternalReturnBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Location.
        /// </summary>
        public static string AddNewLocation {
            get {
                return ResourceManager.GetString("AddNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Delay (minutes).
        /// </summary>
        public static string AlarmDelay {
            get {
                return ResourceManager.GetString("AlarmDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary Cabinets.
        /// </summary>
        public static string AuxillaryCabinets {
            get {
                return ResourceManager.GetString("AuxillaryCabinets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available position.
        /// </summary>
        public static string AvailablePosition {
            get {
                return ResourceManager.GetString("AvailablePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet Configuration.
        /// </summary>
        public static string CabinetConfiguration {
            get {
                return ResourceManager.GetString("CabinetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new Cabinet Controller has been detected.  Would you like to replace controller {0} with {1}?.
        /// </summary>
        public static string CabinetControllerReplacement {
            get {
                return ResourceManager.GetString("CabinetControllerReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string CabinetName {
            get {
                return ResourceManager.GetString("CabinetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet names cannot be empty.
        /// </summary>
        public static string CabinetNamesCannotBeEmpty {
            get {
                return ResourceManager.GetString("CabinetNamesCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet names must be unique.
        /// </summary>
        public static string CabinetNamesMustBeUnique {
            get {
                return ResourceManager.GetString("CabinetNamesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete cabinet device until drawers are removed..
        /// </summary>
        public static string CabinetNotEmpty {
            get {
                return ResourceManager.GetString("CabinetNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet serial numbers.
        /// </summary>
        public static string CabinetSerialNumbers {
            get {
                return ResourceManager.GetString("CabinetSerialNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change configuration..
        /// </summary>
        public static string CannotChangeConfig {
            get {
                return ResourceManager.GetString("CannotChangeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open this tray since the tray number is out of range..
        /// </summary>
        public static string CannotOpenTrayTheTrayNumberIsOutOfRange {
            get {
                return ResourceManager.GetString("CannotOpenTrayTheTrayNumberIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the number of trays for this drawer while there are loaded, pended, or failed trays..
        /// </summary>
        public static string CannotReconfigureMiniDrawer {
            get {
                return ResourceManager.GetString("CannotReconfigureMiniDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string Celcius {
            get {
                return ResourceManager.GetString("Celcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Trays.
        /// </summary>
        public static string ChangeTrays {
            get {
                return ResourceManager.GetString("ChangeTrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the door before selecting another door..
        /// </summary>
        public static string CloseDoorFirst {
            get {
                return ResourceManager.GetString("CloseDoorFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration not saved.
        /// </summary>
        public static string ConfigNotSaved {
            get {
                return ResourceManager.GetString("ConfigNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Cabinets.
        /// </summary>
        public static string ConfigureCabinets {
            get {
                return ResourceManager.GetString("ConfigureCabinets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured.
        /// </summary>
        public static string Configured {
            get {
                return ResourceManager.GetString("Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Remote Stock.
        /// </summary>
        public static string ConfigureRS {
            get {
                return ResourceManager.GetString("ConfigureRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Remote Stock Location.
        /// </summary>
        public static string ConfigureRSL {
            get {
                return ResourceManager.GetString("ConfigureRSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring.
        /// </summary>
        public static string Configuring {
            get {
                return ResourceManager.GetString("Configuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 3x1.
        /// </summary>
        public static string Create3x1Label {
            get {
                return ResourceManager.GetString("Create3x1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Override Options.
        /// </summary>
        public static string CriticalOverrideOptions {
            get {
                return ResourceManager.GetString("CriticalOverrideOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subdrawer is selected..
        /// </summary>
        public static string CUBIE_NoSubDrawerSelected {
            get {
                return ResourceManager.GetString("CUBIE_NoSubDrawerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUBIE Map.
        /// </summary>
        public static string CUBIEMap {
            get {
                return ResourceManager.GetString("CUBIEMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cubie was not saved.
        /// </summary>
        public static string CubieNotSaved {
            get {
                return ResourceManager.GetString("CubieNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please recover the failed cubie and release it before attempting to add a new cubie into the failed position.
        /// </summary>
        public static string CubiePositionIsNotAvailable {
            get {
                return ResourceManager.GetString("CubiePositionIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomLabel {
            get {
                return ResourceManager.GetString("CustomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Location.
        /// </summary>
        public static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMiniTrayLabel {
            get {
                return ResourceManager.GetString("DeleteMiniTrayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The failed device you are replacing is detected on the bus..
        /// </summary>
        public static string DeviceExistsOnBus {
            get {
                return ResourceManager.GetString("DeviceExistsOnBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device failed to open.  Go to Recovery to remedy the problem..
        /// </summary>
        public static string DeviceFailedToOpen {
            get {
                return ResourceManager.GetString("DeviceFailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DonebuttonText {
            get {
                return ResourceManager.GetString("DonebuttonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer Assignment.
        /// </summary>
        public static string DrawerAssignment {
            get {
                return ResourceManager.GetString("DrawerAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer Assignment.
        /// </summary>
        public static string DrawerAssignmentButtonText {
            get {
                return ResourceManager.GetString("DrawerAssignmentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected a failed drawer.  Do you want to replace ID {0} with ID {1} at position {2}?.
        /// </summary>
        public static string DrawerFailedReplacement {
            get {
                return ResourceManager.GetString("DrawerFailedReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected drawer is failed and must be recovered.
        /// </summary>
        public static string DrawerIsFailed {
            get {
                return ResourceManager.GetString("DrawerIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer not assigned. Removed from available drawers list..
        /// </summary>
        public static string DrawerNotAssignedDuringConfiguration {
            get {
                return ResourceManager.GetString("DrawerNotAssignedDuringConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer types must be the same.
        /// </summary>
        public static string DrawerTypeNeedBeSame {
            get {
                return ResourceManager.GetString("DrawerTypeNeedBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate CUBIE serial numbers have been detected.  Go to Recover to remove them from the system..
        /// </summary>
        public static string DuplicateCUBIE_SN_Detected_Recover {
            get {
                return ResourceManager.GetString("DuplicateCUBIE_SN_Detected_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Location.
        /// </summary>
        public static string EditLocation {
            get {
                return ResourceManager.GetString("EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty CUBIE.
        /// </summary>
        public static string EmptyCUBIE {
            get {
                return ResourceManager.GetString("EmptyCUBIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer failed. .
        /// </summary>
        public static string ExceptionDrawerFailed {
            get {
                return ResourceManager.GetString("ExceptionDrawerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray has loaded and pended items..
        /// </summary>
        public static string ExceptionHasLoadedAndPendedItems {
            get {
                return ResourceManager.GetString("ExceptionHasLoadedAndPendedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray has loaded items..
        /// </summary>
        public static string ExceptionHasLoadedItems {
            get {
                return ResourceManager.GetString("ExceptionHasLoadedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray has pended items..
        /// </summary>
        public static string ExceptionHasPendedItems {
            get {
                return ResourceManager.GetString("ExceptionHasPendedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray failed. .
        /// </summary>
        public static string ExceptionTrayFailed {
            get {
                return ResourceManager.GetString("ExceptionTrayFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        public static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility:.
        /// </summary>
        public static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed CUBIE.
        /// </summary>
        public static string FailedCUBIE {
            get {
                return ResourceManager.GetString("FailedCUBIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        public static string Farenheit {
            get {
                return ResourceManager.GetString("Farenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you replacing subdrawer {0} ID:{1} with ID:{2}?.
        /// </summary>
        public static string HalfHeightReplacement {
            get {
                return ResourceManager.GetString("HalfHeightReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the correct permissions to release CUBIE pockets..
        /// </summary>
        public static string IncorrectPermissionToReleaseCubies {
            get {
                return ResourceManager.GetString("IncorrectPermissionToReleaseCubies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to leave the configuration?.
        /// </summary>
        public static string LeaveConfiguration {
            get {
                return ResourceManager.GetString("LeaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower temperature setting must be more than {0}.
        /// </summary>
        public static string LowerTemperatureMinError {
            get {
                return ResourceManager.GetString("LowerTemperatureMinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower temperature must be less than upper temperature limit..
        /// </summary>
        public static string LowerTemperatureUpperTemperatureError {
            get {
                return ResourceManager.GetString("LowerTemperatureUpperTemperatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix drawer heights do not match..
        /// </summary>
        public static string MatrixDrawersDontMatch {
            get {
                return ResourceManager.GetString("MatrixDrawersDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercy Hospital West.
        /// </summary>
        public static string MercyHospitalWest {
            get {
                return ResourceManager.GetString("MercyHospitalWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the middle of configuring drawers.  Press Yes to quit configuring and return to the Cabinet Configuration page..
        /// </summary>
        public static string MiddleOfConfiguration {
            get {
                return ResourceManager.GetString("MiddleOfConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Drawer Configuration.
        /// </summary>
        public static string MiniDrawerConfiguration {
            get {
                return ResourceManager.GetString("MiniDrawerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini drawer tray configurations do not match..
        /// </summary>
        public static string MiniDrawersDontMatch {
            get {
                return ResourceManager.GetString("MiniDrawersDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Tray Configuration.
        /// </summary>
        public static string MiniTrayConfiguration {
            get {
                return ResourceManager.GetString("MiniTrayConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left.
        /// </summary>
        public static string MoveLeft {
            get {
                return ResourceManager.GetString("MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right.
        /// </summary>
        public static string MoveRight {
            get {
                return ResourceManager.GetString("MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs config.
        /// </summary>
        public static string NeedsConfiguration {
            get {
                return ResourceManager.GetString("NeedsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A location name and pocket count are required before editing or adding a location..
        /// </summary>
        public static string NeedToEnterBothNameAndPockets {
            get {
                return ResourceManager.GetString("NeedToEnterBothNameAndPockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drawer at that position..
        /// </summary>
        public static string NoDrawer {
            get {
                return ResourceManager.GetString("NoDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more devices to assign..
        /// </summary>
        public static string NoMoreDevicesToAssign {
            get {
                return ResourceManager.GetString("NoMoreDevicesToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more sub-drawer positions are available..
        /// </summary>
        public static string NoMorePositionsAvailable {
            get {
                return ResourceManager.GetString("NoMorePositionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pockets.
        /// </summary>
        public static string NumberOfPockets {
            get {
                return ResourceManager.GetString("NumberOfPockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open door.
        /// </summary>
        public static string OpenDoor {
            get {
                return ResourceManager.GetString("OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open drawer.
        /// </summary>
        public static string OpenDrawer {
            get {
                return ResourceManager.GetString("OpenDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenTrayLabel {
            get {
                return ResourceManager.GetString("OpenTrayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Care Area:.
        /// </summary>
        public static string PatientCareArea {
            get {
                return ResourceManager.GetString("PatientCareArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pediatrics.
        /// </summary>
        public static string Pediatrics {
            get {
                return ResourceManager.GetString("Pediatrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pediatrics, ER, Private Care.
        /// </summary>
        public static string PediatricsERPrivateCare {
            get {
                return ResourceManager.GetString("PediatricsERPrivateCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending/Loaded.
        /// </summary>
        public static string PendingLoaded {
            get {
                return ResourceManager.GetString("PendingLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close open tray first..
        /// </summary>
        public static string PleaseCloseTray {
            get {
                return ResourceManager.GetString("PleaseCloseTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pockets.
        /// </summary>
        public static string Pockets {
            get {
                return ResourceManager.GetString("Pockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0}.
        /// </summary>
        public static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That position is already taken..
        /// </summary>
        public static string PositionTaken {
            get {
                return ResourceManager.GetString("PositionTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to configure.
        /// </summary>
        public static string PressToConfigure {
            get {
                return ResourceManager.GetString("PressToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Stock.
        /// </summary>
        public static string RemoteStockButtonText {
            get {
                return ResourceManager.GetString("RemoteStockButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Stock Location Name.
        /// </summary>
        public static string RemoteStockLocationName {
            get {
                return ResourceManager.GetString("RemoteStockLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Stock location name is too long..
        /// </summary>
        public static string RemoteStockLocationNameTooLong {
            get {
                return ResourceManager.GetString("RemoteStockLocationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Stock name must be unique..
        /// </summary>
        public static string RemoteStockNameMustBeUnique {
            get {
                return ResourceManager.GetString("RemoteStockNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Cabinet.
        /// </summary>
        public static string RemoveCabinet {
            get {
                return ResourceManager.GetString("RemoveCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Interval (minutes).
        /// </summary>
        public static string ReportingInterval {
            get {
                return ResourceManager.GetString("ReportingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report interval must be less than {0}.
        /// </summary>
        public static string ReportingIntervalMaxError {
            get {
                return ResourceManager.GetString("ReportingIntervalMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report interval must be more than {0}.
        /// </summary>
        public static string ReportingIntervalMinError {
            get {
                return ResourceManager.GetString("ReportingIntervalMinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a Return Bin when the cabinet already has one..
        /// </summary>
        public static string ReturnBin_AlreadyInCabinet {
            get {
                return ResourceManager.GetString("ReturnBin_AlreadyInCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANNOT ASSIGN: Cannot add a Return Bin when the cabinet already has one..
        /// </summary>
        public static string ReturnBin_CANNOT_ASSIGN {
            get {
                return ResourceManager.GetString("ReturnBin_CANNOT_ASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANNOT UNASSIGN.
        /// </summary>
        public static string ReturnBin_CANNOT_UNASSIGN {
            get {
                return ResourceManager.GetString("ReturnBin_CANNOT_UNASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a Return Bin when the drawer isn&apos;t empty..
        /// </summary>
        public static string ReturnBin_DrawerNotEmpty {
            get {
                return ResourceManager.GetString("ReturnBin_DrawerNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the Return Bin because it is not empty..
        /// </summary>
        public static string ReturnBin_NotEmptyForRemoval {
            get {
                return ResourceManager.GetString("ReturnBin_NotEmptyForRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAllTraysLabel {
            get {
                return ResourceManager.GetString("SelectAllTraysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Door to configure.
        /// </summary>
        public static string SelectDoorToConfigure {
            get {
                return ResourceManager.GetString("SelectDoorToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string SelectNoneTraysLabel {
            get {
                return ResourceManager.GetString("SelectNoneTraysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Remote Stock location  needs to be selected before deleting..
        /// </summary>
        public static string SelectRemoteStockBeforeDeleting {
            get {
                return ResourceManager.GetString("SelectRemoteStockBeforeDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Remote Stock location needs to be selected before editing..
        /// </summary>
        public static string SelectRemoteStockBeforeEditing {
            get {
                return ResourceManager.GetString("SelectRemoteStockBeforeEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMART Remote Settings.
        /// </summary>
        public static string SMARTRemoteSettings {
            get {
                return ResourceManager.GetString("SMARTRemoteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space location contains meds that need to be unloaded..
        /// </summary>
        public static string StorageSpaceNotEmpty {
            get {
                return ResourceManager.GetString("StorageSpaceNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved device settings.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to 6 Drawers.
        /// </summary>
        public static string SwitchToSixDrawer {
            get {
                return ResourceManager.GetString("SwitchToSixDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to 2 Drawers.
        /// </summary>
        public static string SwitchToTwoDrawer {
            get {
                return ResourceManager.GetString("SwitchToTwoDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to 0 Drawers.
        /// </summary>
        public static string SwitchToZeroDrawer {
            get {
                return ResourceManager.GetString("SwitchToZeroDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Range: .
        /// </summary>
        public static string TemperatureRange {
            get {
                return ResourceManager.GetString("TemperatureRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray is not available. .
        /// </summary>
        public static string TrayIsNotAvailable {
            get {
                return ResourceManager.GetString("TrayIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add new remote stock location..
        /// </summary>
        public static string UnableToAddRemoteStock {
            get {
                return ResourceManager.GetString("UnableToAddRemoteStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper temperature setting must be less than {0}.
        /// </summary>
        public static string UpperTemperatureMaxError {
            get {
                return ResourceManager.GetString("UpperTemperatureMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning delay must be less than {0}.
        /// </summary>
        public static string WarningDelayMaxError {
            get {
                return ResourceManager.GetString("WarningDelayMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning delay must be more than {0}.
        /// </summary>
        public static string WarningDelayMinimumError {
            get {
                return ResourceManager.GetString("WarningDelayMinimumError", resourceCulture);
            }
        }
    }
}
