//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Common.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication is blocked by pharmacy.
        /// </summary>
        public static string AssignableMedItemNotActionableReason_Blocked {
            get {
                return ResourceManager.GetString("AssignableMedItemNotActionableReason_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item needs to be scanned.
        /// </summary>
        public static string AssignableMedItemNotActionableReason_ItemRequiresScan {
            get {
                return ResourceManager.GetString("AssignableMedItemNotActionableReason_ItemRequiresScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space has pended items.
        /// </summary>
        public static string AssignableStorageSpaceNotActionableReason_ItemPended {
            get {
                return ResourceManager.GetString("AssignableStorageSpaceNotActionableReason_ItemPended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pend over Standard Stock.
        /// </summary>
        public static string AssignableStorageSpaceNotActionableReason_NoPendOverStandardStock {
            get {
                return ResourceManager.GetString("AssignableStorageSpaceNotActionableReason_NoPendOverStandardStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string AssignableStorageSpaceNotActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("AssignableStorageSpaceNotActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is blocked.
        /// </summary>
        public static string AssignableStorageSpaceNotActionableReason_StorageSpaceBlocked {
            get {
                return ResourceManager.GetString("AssignableStorageSpaceNotActionableReason_StorageSpaceBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting.
        /// </summary>
        public static string AssignableStorageSpaceNotActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("AssignableStorageSpaceNotActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed.
        /// </summary>
        public static string AssignableStorageSpaceNotActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("AssignableStorageSpaceNotActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string AssignableStorageSpaceNotActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("AssignableStorageSpaceNotActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pended items in this drawer require unload.  Please load from Load/Refill Function..
        /// </summary>
        public static string AutoloadNotActionableReason_PendedOnLoadedPocket {
            get {
                return ResourceManager.GetString("AutoloadNotActionableReason_PendedOnLoadedPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pended items in this drawer require unload or inventory reference number(s).  Please load from Load/Refill Function..
        /// </summary>
        public static string AutoloadNotActionableReason_PendedOnLoadedRequireReferenceNum {
            get {
                return ResourceManager.GetString("AutoloadNotActionableReason_PendedOnLoadedRequireReferenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pended items in this drawer require inventory reference number(s).  Please load from Load/Refill Function..
        /// </summary>
        public static string AutoloadNotActionableReason_RequireReferenceNumber {
            get {
                return ResourceManager.GetString("AutoloadNotActionableReason_RequireReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have permission to complete the workflow.
        /// </summary>
        public static string CompoundNonActionableReason_NoAcess {
            get {
                return ResourceManager.GetString("CompoundNonActionableReason_NoAcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to destock this item..
        /// </summary>
        public static string DestockNotActionableReason_CannotDestock {
            get {
                return ResourceManager.GetString("DestockNotActionableReason_CannotDestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to open the drawer..
        /// </summary>
        public static string DestockNotActionableReason_NoOpenDrawerPermission {
            get {
                return ResourceManager.GetString("DestockNotActionableReason_NoOpenDrawerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string DestockNotActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("DestockNotActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting..
        /// </summary>
        public static string DestockNotActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("DestockNotActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed..
        /// </summary>
        public static string DestockNotActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("DestockNotActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string DestockNotActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("DestockNotActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device failed to lock.
        /// </summary>
        public static string DeviceFailureEventReason_DeviceFailedToLock {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_DeviceFailedToLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device failed to open.
        /// </summary>
        public static string DeviceFailureEventReason_DeviceFailedToOpen {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_DeviceFailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device failed to release.
        /// </summary>
        public static string DeviceFailureEventReason_DeviceFailedToRelease {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_DeviceFailedToRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device failed to stay closed.
        /// </summary>
        public static string DeviceFailureEventReason_DeviceFailedToStayClosed {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_DeviceFailedToStayClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device failed to unlock.
        /// </summary>
        public static string DeviceFailureEventReason_DeviceFailedToUnlock {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_DeviceFailedToUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General hardware failure.
        /// </summary>
        public static string DeviceFailureEventReason_DeviceGeneralFailure {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_DeviceGeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device latch ambiguous.
        /// </summary>
        public static string DeviceFailureEventReason_DeviceLatchAmbiguous {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_DeviceLatchAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found.
        /// </summary>
        public static string DeviceFailureEventReason_DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini tray overspeed error.
        /// </summary>
        public static string DeviceFailureEventReason_MiniTrayOverspeedError {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_MiniTrayOverspeedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini tray shorted or open solenoid circuit.
        /// </summary>
        public static string DeviceFailureEventReason_MiniTrayShortedOrOpenSolenoidCircuit {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_MiniTrayShortedOrOpenSolenoidCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini tray timeout.
        /// </summary>
        public static string DeviceFailureEventReason_MiniTrayTimeout {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_MiniTrayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown hardware failure.
        /// </summary>
        public static string DeviceFailureEventReason_None {
            get {
                return ResourceManager.GetString("DeviceFailureEventReason_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired CS License .
        /// </summary>
        public static string DeviceItemNonActionableReason_CSLicenseExpired {
            get {
                return ResourceManager.GetString("DeviceItemNonActionableReason_CSLicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Service Device.
        /// </summary>
        public static string DeviceItemNonActionableReason_OutOfService {
            get {
                return ResourceManager.GetString("DeviceItemNonActionableReason_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backordered.
        /// </summary>
        public static string DispenseMedNotActionableReason_Backordered {
            get {
                return ResourceManager.GetString("DispenseMedNotActionableReason_Backordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication is blocked by pharmacy.
        /// </summary>
        public static string DispenseMedNotActionableReason_Blocked {
            get {
                return ResourceManager.GetString("DispenseMedNotActionableReason_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Med.
        /// </summary>
        public static string DispenseMedNotActionableReason_Inactive {
            get {
                return ResourceManager.GetString("DispenseMedNotActionableReason_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med in failed storage space.
        /// </summary>
        public static string DispenseMedNotActionableReason_InFailedStorageUnit {
            get {
                return ResourceManager.GetString("DispenseMedNotActionableReason_InFailedStorageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not loaded.
        /// </summary>
        public static string DispenseMedNotActionableReason_NotLoaded {
            get {
                return ResourceManager.GetString("DispenseMedNotActionableReason_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication is unavailable to dispense to My Items.
        /// </summary>
        public static string DispenseMedNotActionableReason_NotMyItems {
            get {
                return ResourceManager.GetString("DispenseMedNotActionableReason_NotMyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        public static string DispenseMedNotActionableReason_OutOfStock {
            get {
                return ResourceManager.GetString("DispenseMedNotActionableReason_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access.
        /// </summary>
        public static string DispenseMedNotActionableReason_RestrictedAccess {
            get {
                return ResourceManager.GetString("DispenseMedNotActionableReason_RestrictedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to open the drawer.
        /// </summary>
        public static string InventoryCountNotActionableReason_NoOpenDrawerPermission {
            get {
                return ResourceManager.GetString("InventoryCountNotActionableReason_NoOpenDrawerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string InventoryCountNotActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("InventoryCountNotActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting.
        /// </summary>
        public static string InventoryCountNotActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("InventoryCountNotActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed.
        /// </summary>
        public static string InventoryCountNotActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("InventoryCountNotActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string InventoryCountNotActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("InventoryCountNotActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is already selected.
        /// </summary>
        public static string InvoiceNotActionableReason_AlreadySelected {
            get {
                return ResourceManager.GetString("InvoiceNotActionableReason_AlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired CS License.
        /// </summary>
        public static string IssueNonActionableReason_CSLicenseExpired {
            get {
                return ResourceManager.GetString("IssueNonActionableReason_CSLicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The medication is not available in the device&apos;s facility.
        /// </summary>
        public static string IssueNonActionableReason_MedItemNotAvailable {
            get {
                return ResourceManager.GetString("IssueNonActionableReason_MedItemNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Service Device.
        /// </summary>
        public static string IssueNonActionableReason_OutOfService {
            get {
                return ResourceManager.GetString("IssueNonActionableReason_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is already selected.
        /// </summary>
        public static string IssueNonActionableReason_Selected {
            get {
                return ResourceManager.GetString("IssueNonActionableReason_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication is blocked by pharmacy.
        /// </summary>
        public static string LoadRefillNotActionableReason_Blocked {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item cannot be loaded due to conflicting Remove Fractional Unit setting..
        /// </summary>
        public static string LoadRefillNotActionableReason_FractionalConflict {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_FractionalConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to open the drawer.
        /// </summary>
        public static string LoadRefillNotActionableReason_NoOpenDrawerPermission {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_NoOpenDrawerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string LoadRefillNotActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting.
        /// </summary>
        public static string LoadRefillNotActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed.
        /// </summary>
        public static string LoadRefillNotActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string LoadRefillNotActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to unload the item in this storage location before loading.  The unload item is blocked..
        /// </summary>
        public static string LoadRefillNotActionableReason_UnloadOnLoadBlocked {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_UnloadOnLoadBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to unload the item in this storage location before loading.  You don&apos;t have unload permission during load and refill..
        /// </summary>
        public static string LoadRefillNotActionableReason_UnloadOnLoadWithoutPermission {
            get {
                return ResourceManager.GetString("LoadRefillNotActionableReason_UnloadOnLoadWithoutPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        public static string MiniDrawerTrayModeInternalCode_MATRIX {
            get {
                return ResourceManager.GetString("MiniDrawerTrayModeInternalCode_MATRIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi dose.
        /// </summary>
        public static string MiniDrawerTrayModeInternalCode_MULTIDOSE {
            get {
                return ResourceManager.GetString("MiniDrawerTrayModeInternalCode_MULTIDOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single dose.
        /// </summary>
        public static string MiniDrawerTrayModeInternalCode_SINGLEDOSE {
            get {
                return ResourceManager.GetString("MiniDrawerTrayModeInternalCode_SINGLEDOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to this item.
        /// </summary>
        public static string MyKitNotActionableReason_NoRemovePermission {
            get {
                return ResourceManager.GetString("MyKitNotActionableReason_NoRemovePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to open the drawer.
        /// </summary>
        public static string OutdateNotActionableReason_NoOpenDrawerPermission {
            get {
                return ResourceManager.GetString("OutdateNotActionableReason_NoOpenDrawerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string OutdateNotActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("OutdateNotActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdate tracking is not enabled for this item.
        /// </summary>
        public static string OutdateNotActionableReason_NotTrackingOutdate {
            get {
                return ResourceManager.GetString("OutdateNotActionableReason_NotTrackingOutdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting.
        /// </summary>
        public static string OutdateNotActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("OutdateNotActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed.
        /// </summary>
        public static string OutdateNotActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("OutdateNotActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string OutdateNotActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("OutdateNotActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been returned/wasted/transferred in full.
        /// </summary>
        public static string PatientCaseNotActionableReasons_ZeroTransactionAmount {
            get {
                return ResourceManager.GetString("PatientCaseNotActionableReasons_ZeroTransactionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already selected.
        /// </summary>
        public static string ReallocateNonActionableReason_AlreadySelected {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_AlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication is blocked by pharmacy.
        /// </summary>
        public static string ReallocateNonActionableReason_Blocked {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubie is not available for selection.
        /// </summary>
        public static string ReallocateNonActionableReason_CubieNotSelectable {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_CubieNotSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication is expired.
        /// </summary>
        public static string ReallocateNonActionableReason_ExpiredMed {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_ExpiredMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is full.
        /// </summary>
        public static string ReallocateNonActionableReason_FillToMaxIsZero {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_FillToMaxIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item cannot be received due to conflicting Receive Fractional Unit setting..
        /// </summary>
        public static string ReallocateNonActionableReason_FractionalConflict {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_FractionalConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        public static string ReallocateNonActionableReason_NoInventoryAvailable {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_NoInventoryAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access the med.
        /// </summary>
        public static string ReallocateNonActionableReason_NoMedAccess {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_NoMedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to open the drawer.
        /// </summary>
        public static string ReallocateNonActionableReason_NoOpenDrawerPermission {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_NoOpenDrawerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string ReallocateNonActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting.
        /// </summary>
        public static string ReallocateNonActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed.
        /// </summary>
        public static string ReallocateNonActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space not available.
        /// </summary>
        public static string ReallocateNonActionableReason_StorageSpaceNotAvailable {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_StorageSpaceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string ReallocateNonActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("ReallocateNonActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already selected.
        /// </summary>
        public static string ReceiveNonActionableReason_AlreadySelected {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_AlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication is blocked by pharmacy.
        /// </summary>
        public static string ReceiveNonActionableReason_Blocked {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubie is not available for selection.
        /// </summary>
        public static string ReceiveNonActionableReason_CubieNotSelectable {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_CubieNotSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is full.
        /// </summary>
        public static string ReceiveNonActionableReason_FillToMaxIsZero {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_FillToMaxIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item cannot be received due to conflicting Receive Fractional Unit setting..
        /// </summary>
        public static string ReceiveNonActionableReason_FractionalConflict {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_FractionalConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Med.
        /// </summary>
        public static string ReceiveNonActionableReason_InactiveMed {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_InactiveMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this item.
        /// </summary>
        public static string ReceiveNonActionableReason_NoMedAccess {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_NoMedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to open the drawer.
        /// </summary>
        public static string ReceiveNonActionableReason_NoOpenDrawerPermission {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_NoOpenDrawerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string ReceiveNonActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med Not Approved.
        /// </summary>
        public static string ReceiveNonActionableReason_NotApproved {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item needs to be scanned.
        /// </summary>
        public static string ReceiveNonActionableReason_ScanItemRequired {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_ScanItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting.
        /// </summary>
        public static string ReceiveNonActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed.
        /// </summary>
        public static string ReceiveNonActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space not available.
        /// </summary>
        public static string ReceiveNonActionableReason_StorageSpaceNotAvailable {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_StorageSpaceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string ReceiveNonActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("ReceiveNonActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string RxCheckNotActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("RxCheckNotActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting..
        /// </summary>
        public static string RxCheckNotActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("RxCheckNotActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed..
        /// </summary>
        public static string RxCheckNotActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("RxCheckNotActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string RxCheckNotActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("RxCheckNotActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired CS License.
        /// </summary>
        public static string SellLocationNonActionableReason_CSLicenseExpired {
            get {
                return ResourceManager.GetString("SellLocationNonActionableReason_CSLicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device battery does not have enough power to recover.
        /// </summary>
        public static string StorageSpaceRecoveryNotActionableReason_BatteryDepleted {
            get {
                return ResourceManager.GetString("StorageSpaceRecoveryNotActionableReason_BatteryDepleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string StorageSpaceRecoveryNotActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("StorageSpaceRecoveryNotActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Cabinet contains an unsecured bin that needs to be recovered first.
        /// </summary>
        public static string StorageSpaceRecoveryNotActionableReason_RecoverOpenBinFirst {
            get {
                return ResourceManager.GetString("StorageSpaceRecoveryNotActionableReason_RecoverOpenBinFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer contains an unsecured CUBIE that needs to be recovered first.
        /// </summary>
        public static string StorageSpaceRecoveryNotActionableReason_RecoverOpenCUBIEFirst {
            get {
                return ResourceManager.GetString("StorageSpaceRecoveryNotActionableReason_RecoverOpenCUBIEFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrigerator does not have enough power to recover.
        /// </summary>
        public static string StorageSpaceRecoveryNotActionableReason_RefrigeratorPowerLoss {
            get {
                return ResourceManager.GetString("StorageSpaceRecoveryNotActionableReason_RefrigeratorPowerLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backordered.
        /// </summary>
        public static string TakeOutNonActionableReason_Backordered {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_Backordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication is blocked by pharmacy.
        /// </summary>
        public static string TakeOutNonActionableReason_Blocked {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Med.
        /// </summary>
        public static string TakeOutNonActionableReason_InactiveMedication {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_InactiveMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med in defrosting storage space.
        /// </summary>
        public static string TakeOutNonActionableReason_InDefrostingStorageUnit {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_InDefrostingStorageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med in failed storage space.
        /// </summary>
        public static string TakeOutNonActionableReason_InFailedStorageUnit {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_InFailedStorageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string TakeOutNonActionableReason_InOutOfServiceStorageUnit {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_InOutOfServiceStorageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient quantity.
        /// </summary>
        public static string TakeOutNonActionableReason_InsufficientQuantity {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_InsufficientQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The medication is not available in the device&apos;s facility.
        /// </summary>
        public static string TakeOutNonActionableReason_MedItemNotAvailable {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_MedItemNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some meds have not been approved or are deleted.
        /// </summary>
        public static string TakeOutNonActionableReason_MissingComponent {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_MissingComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med Not Approved.
        /// </summary>
        public static string TakeOutNonActionableReason_NotApproved {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not loaded.
        /// </summary>
        public static string TakeOutNonActionableReason_NotLoaded {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        public static string TakeOutNonActionableReason_OutOfStock {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access.
        /// </summary>
        public static string TakeOutNonActionableReason_RestrictedAccess {
            get {
                return ResourceManager.GetString("TakeOutNonActionableReason_RestrictedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Selected.
        /// </summary>
        public static string TransactionNonActionableReason_AlreadySelected {
            get {
                return ResourceManager.GetString("TransactionNonActionableReason_AlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Outstanding.
        /// </summary>
        public static string TransactionNonActionableReason_NoOutstanding {
            get {
                return ResourceManager.GetString("TransactionNonActionableReason_NoOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Permission.
        /// </summary>
        public static string TransactionNonActionableReason_NoPermission {
            get {
                return ResourceManager.GetString("TransactionNonActionableReason_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to open the drawer.
        /// </summary>
        public static string UnloadNotActionableReason_NoOpenDrawerPermission {
            get {
                return ResourceManager.GetString("UnloadNotActionableReason_NoOpenDrawerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access one or more items in the storage unit..
        /// </summary>
        public static string UnloadNotActionableReason_NoStorageSpaceAccess {
            get {
                return ResourceManager.GetString("UnloadNotActionableReason_NoStorageSpaceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is defrosting.
        /// </summary>
        public static string UnloadNotActionableReason_StorageSpaceDefrosting {
            get {
                return ResourceManager.GetString("UnloadNotActionableReason_StorageSpaceDefrosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is failed.
        /// </summary>
        public static string UnloadNotActionableReason_StorageSpaceFailed {
            get {
                return ResourceManager.GetString("UnloadNotActionableReason_StorageSpaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage space is out of service.
        /// </summary>
        public static string UnloadNotActionableReason_StorageSpaceOutOfService {
            get {
                return ResourceManager.GetString("UnloadNotActionableReason_StorageSpaceOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is expired.
        /// </summary>
        public static string UserNotActionableReason_Expired {
            get {
                return ResourceManager.GetString("UserNotActionableReason_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has access.
        /// </summary>
        public static string UserNotActionableReason_HasAccessToAllAreas {
            get {
                return ResourceManager.GetString("UserNotActionableReason_HasAccessToAllAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is inactive.
        /// </summary>
        public static string UserNotActionableReason_Inactive {
            get {
                return ResourceManager.GetString("UserNotActionableReason_Inactive", resourceCulture);
            }
        }
    }
}
