//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Common.ReportsResources", typeof(ReportsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All below max.
        /// </summary>
        public static string AllBelowMaxTitle {
            get {
                return ResourceManager.GetString("AllBelowMaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Devices.
        /// </summary>
        public static string AllDeviceTitle {
            get {
                return ResourceManager.GetString("AllDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string AllStationEvents {
            get {
                return ResourceManager.GetString("AllStationEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At or below min.
        /// </summary>
        public static string AtOrBelowMinTitle {
            get {
                return ResourceManager.GetString("AtOrBelowMinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning.
        /// </summary>
        public static string Beginning {
            get {
                return ResourceManager.GetString("Beginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelTitle {
            get {
                return ResourceManager.GetString("CancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string CarrentPageFormat {
            get {
                return ResourceManager.GetString("CarrentPageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Report.
        /// </summary>
        public static string CompareReport {
            get {
                return ResourceManager.GetString("CompareReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} days.
        /// </summary>
        public static string DateRangeFormat {
            get {
                return ResourceManager.GetString("DateRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refill Delivery Report.
        /// </summary>
        public static string DeliveryPickReportTitle {
            get {
                return ResourceManager.GetString("DeliveryPickReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string DeviceTitle {
            get {
                return ResourceManager.GetString("DeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy.
        /// </summary>
        public static string Discrepancy {
            get {
                return ResourceManager.GetString("Discrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy Created.
        /// </summary>
        public static string DiscrepancyCreated {
            get {
                return ResourceManager.GetString("DiscrepancyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy Resolved.
        /// </summary>
        public static string DiscrepancyResolved {
            get {
                return ResourceManager.GetString("DiscrepancyResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy Transaction Report.
        /// </summary>
        public static string DiscrepancyTransactionReport {
            get {
                return ResourceManager.GetString("DiscrepancyTransactionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documented.
        /// </summary>
        public static string Documented {
            get {
                return ResourceManager.GetString("Documented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string EndDateLable {
            get {
                return ResourceManager.GetString("EndDateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select End Date.
        /// </summary>
        public static string EndDateTitle {
            get {
                return ResourceManager.GetString("EndDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending.
        /// </summary>
        public static string Ending {
            get {
                return ResourceManager.GetString("Ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following Transactions.
        /// </summary>
        public static string FollowingTransactions {
            get {
                return ResourceManager.GetString("FollowingTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by: .
        /// </summary>
        public static string GroupedBy {
            get {
                return ResourceManager.GetString("GroupedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}].
        /// </summary>
        public static string IDMedTitleFormat {
            get {
                return ResourceManager.GetString("IDMedTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} ({2}).
        /// </summary>
        public static string IDTitleFormat {
            get {
                return ResourceManager.GetString("IDTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string IDTitleShortFormat {
            get {
                return ResourceManager.GetString("IDTitleShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in report:.
        /// </summary>
        public static string IncludeInReportTitle {
            get {
                return ResourceManager.GetString("IncludeInReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string InventoryByStation {
            get {
                return ResourceManager.GetString("InventoryByStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Report.
        /// </summary>
        public static string InventoryReportTitle {
            get {
                return ResourceManager.GetString("InventoryReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med.
        /// </summary>
        public static string MedTitle {
            get {
                return ResourceManager.GetString("MedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameHeaderTitle {
            get {
                return ResourceManager.GetString("NameHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item(s) selected.
        /// </summary>
        public static string NoItemSelected {
            get {
                return ResourceManager.GetString("NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None selected.
        /// </summary>
        public static string NoneSelectedLabel {
            get {
                return ResourceManager.GetString("NoneSelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Outdated Meds.
        /// </summary>
        public static string OutdatedMedsOnly {
            get {
                return ResourceManager.GetString("OutdatedMedsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Down.
        /// </summary>
        public static string PageDown {
            get {
                return ResourceManager.GetString("PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Up.
        /// </summary>
        public static string PageUp {
            get {
                return ResourceManager.GetString("PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Case.
        /// </summary>
        public static string PatientCase {
            get {
                return ResourceManager.GetString("PatientCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Case Events.
        /// </summary>
        public static string PatientCaseEvents {
            get {
                return ResourceManager.GetString("PatientCaseEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string PatientsTitle {
            get {
                return ResourceManager.GetString("PatientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string PatientTitle {
            get {
                return ResourceManager.GetString("PatientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} {2} (DOB:{3}) {4} (ID: {5}).
        /// </summary>
        public static string PatientTitleFormat {
            get {
                return ResourceManager.GetString("PatientTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refill Delivery.
        /// </summary>
        public static string PickDelivery {
            get {
                return ResourceManager.GetString("PickDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed.
        /// </summary>
        public static string Printed {
            get {
                return ResourceManager.GetString("Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prior Transactions.
        /// </summary>
        public static string PriorTransactions {
            get {
                return ResourceManager.GetString("PriorTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refill Pick.
        /// </summary>
        public static string RefillDelivery {
            get {
                return ResourceManager.GetString("RefillDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refill Pick Report.
        /// </summary>
        public static string RefillPickReportTitle {
            get {
                return ResourceManager.GetString("RefillPickReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report end date cannot be empty.
        /// </summary>
        public static string ReportEndDateCannotBeEmpty {
            get {
                return ResourceManager.GetString("ReportEndDateCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report end date cannot be {0} days greater than report start date.
        /// </summary>
        public static string ReportEndDateCannotBeGreaterThanStartDateBy31 {
            get {
                return ResourceManager.GetString("ReportEndDateCannotBeGreaterThanStartDateBy31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report end date can not be greater than today&apos;s date.
        /// </summary>
        public static string ReportEndDateCannotBeGreaterThanToday {
            get {
                return ResourceManager.GetString("ReportEndDateCannotBeGreaterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report end date is not a valid date.
        /// </summary>
        public static string ReportEndDateIsnotValidDate {
            get {
                return ResourceManager.GetString("ReportEndDateIsnotValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Preview.
        /// </summary>
        public static string ReportPreview {
            get {
                return ResourceManager.GetString("ReportPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report start date cannot be {0} days earlier than today.
        /// </summary>
        public static string ReportStartDateCannotBeEarlierThanTodayBy31Days {
            get {
                return ResourceManager.GetString("ReportStartDateCannotBeEarlierThanTodayBy31Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report start date cannot be empty.
        /// </summary>
        public static string ReportStartDateCannotBeEmpty {
            get {
                return ResourceManager.GetString("ReportStartDateCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report start date cannot be greater than report end date.
        /// </summary>
        public static string ReportStartDateCannotBeGreaterThanEndDate {
            get {
                return ResourceManager.GetString("ReportStartDateCannotBeGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report start date is not a valid date.
        /// </summary>
        public static string ReportStartDateIsnotValidDate {
            get {
                return ResourceManager.GetString("ReportStartDateIsnotValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved Discrepancy.
        /// </summary>
        public static string ResolvedDiscrepancy {
            get {
                return ResourceManager.GetString("ResolvedDiscrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Report.
        /// </summary>
        public static string RunReportTitle {
            get {
                return ResourceManager.GetString("RunReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        public static string StartDateLable {
            get {
                return ResourceManager.GetString("StartDateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Start Date.
        /// </summary>
        public static string StartDateTitle {
            get {
                return ResourceManager.GetString("StartDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Events Report.
        /// </summary>
        public static string StationEventsReportTitle {
            get {
                return ResourceManager.GetString("StationEventsReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string StationTitle {
            get {
                return ResourceManager.GetString("StationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage location.
        /// </summary>
        public static string StorageTitle {
            get {
                return ResourceManager.GetString("StorageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Area.
        /// </summary>
        public static string TabNameArea {
            get {
                return ResourceManager.GetString("TabNameArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer.
        /// </summary>
        public static string TabNameDrawer {
            get {
                return ResourceManager.GetString("TabNameDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med Class.
        /// </summary>
        public static string TabNameMedClass {
            get {
                return ResourceManager.GetString("TabNameMedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meds.
        /// </summary>
        public static string TabNameMeds {
            get {
                return ResourceManager.GetString("TabNameMeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temporary.
        /// </summary>
        public static string TemporaryID {
            get {
                return ResourceManager.GetString("TemporaryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Device.
        /// </summary>
        public static string ThisDeviceTitle {
            get {
                return ResourceManager.GetString("ThisDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today only.
        /// </summary>
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tx Type.
        /// </summary>
        public static string TxType {
            get {
                return ResourceManager.GetString("TxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersTitle {
            get {
                return ResourceManager.GetString("UsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness.
        /// </summary>
        public static string Witness {
            get {
                return ResourceManager.GetString("Witness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string ZoneTitle {
            get {
                return ResourceManager.GetString("ZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
