//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StorageSpaceConfigResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StorageSpaceConfigResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.Common.StorageSpaceConfigResources", typeof(StorageSpaceConfigResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Order.
        /// </summary>
        public static string AccessOrder {
            get {
                return ResourceManager.GetString("AccessOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Aux Cabinet.
        /// </summary>
        public static string AddAuxCabinet {
            get {
                return ResourceManager.GetString("AddAuxCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Excess Stock.
        /// </summary>
        public static string AddExcess {
            get {
                return ResourceManager.GetString("AddExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destruction Bin.
        /// </summary>
        public static string AddExtReturnBin {
            get {
                return ResourceManager.GetString("AddExtReturnBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Integrated Main.
        /// </summary>
        public static string AddIntegratedMain {
            get {
                return ResourceManager.GetString("AddIntegratedMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Main Cabinet.
        /// </summary>
        public static string AddMainCabinet {
            get {
                return ResourceManager.GetString("AddMainCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remote Stock.
        /// </summary>
        public static string AddRemoteStock {
            get {
                return ResourceManager.GetString("AddRemoteStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Drawers.
        /// </summary>
        public static string AssignDrawers {
            get {
                return ResourceManager.GetString("AssignDrawers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aux Cabinet.
        /// </summary>
        public static string AuxCabinet {
            get {
                return ResourceManager.GetString("AuxCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Height Accessible Matrix ({0}).
        /// </summary>
        public static string BinHeightAccessibleMatrixCountFormat {
            get {
                return ResourceManager.GetString("BinHeightAccessibleMatrixCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Height Matrix ({0}).
        /// </summary>
        public static string BinHeightMatrixCountFormat {
            get {
                return ResourceManager.GetString("BinHeightMatrixCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet Name*.
        /// </summary>
        public static string CabinetName {
            get {
                return ResourceManager.GetString("CabinetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet Settings.
        /// </summary>
        public static string CabinetSettings {
            get {
                return ResourceManager.GetString("CabinetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change configuraton for loaded or pended trays.
        /// </summary>
        public static string CannotChangeConfigurationForLoadedPendedTrays {
            get {
                return ResourceManager.GetString("CannotChangeConfigurationForLoadedPendedTrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cannot pocket count for loaded or pended trays.
        /// </summary>
        public static string CannotChangePocketCountForLoadePendedTrays {
            get {
                return ResourceManager.GetString("CannotChangePocketCountForLoadePendedTrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change pocket when drawer is open.
        /// </summary>
        public static string CannotChangePocketCountWhenDrawerOpen {
            get {
                return ResourceManager.GetString("CannotChangePocketCountWhenDrawerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the door before continuing.
        /// </summary>
        public static string CloseDoorBeforeContinuing {
            get {
                return ResourceManager.GetString("CloseDoorBeforeContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the drawer to commit assignment.
        /// </summary>
        public static string CloseDrawer {
            get {
                return ResourceManager.GetString("CloseDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close drawer to continue with stopping..
        /// </summary>
        public static string CloseDrawerBeforeStopping {
            get {
                return ResourceManager.GetString("CloseDrawerBeforeStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first close the drawer to select another item.
        /// </summary>
        public static string CloseDrawerToChangeSelectedItem {
            get {
                return ResourceManager.GetString("CloseDrawerToChangeSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must close the drawer to continue.
        /// </summary>
        public static string CloseDrawerToContinue {
            get {
                return ResourceManager.GetString("CloseDrawerToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the drawer to create trays.
        /// </summary>
        public static string CloseDrawerToCreateTrays {
            get {
                return ResourceManager.GetString("CloseDrawerToCreateTrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first close the drawer to exit.
        /// </summary>
        public static string CloseDrawerToExit {
            get {
                return ResourceManager.GetString("CloseDrawerToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to replace, drawer configurations do not match..
        /// </summary>
        public static string ConfigurationsDontMatch {
            get {
                return ResourceManager.GetString("ConfigurationsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured.
        /// </summary>
        public static string Configured {
            get {
                return ResourceManager.GetString("Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Settings.
        /// </summary>
        public static string CopySettings {
            get {
                return ResourceManager.GetString("CopySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupled with Door {0}.
        /// </summary>
        public static string CoupledWithDoor {
            get {
                return ResourceManager.GetString("CoupledWithDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t couple because one or more doors are not connected.
        /// </summary>
        public static string CoupleNotOnBus {
            get {
                return ResourceManager.GetString("CoupleNotOnBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t couple because one or more of the doors are pended or loaded.
        /// </summary>
        public static string CouplingInventoryWarning {
            get {
                return ResourceManager.GetString("CouplingInventoryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 1x1.
        /// </summary>
        public static string Create1x1 {
            get {
                return ResourceManager.GetString("Create1x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 3x1.
        /// </summary>
        public static string Create3x1 {
            get {
                return ResourceManager.GetString("Create3x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating 1x1 trays.
        /// </summary>
        public static string Creating1x1Trays {
            get {
                return ResourceManager.GetString("Creating1x1Trays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating 3x1 trays.
        /// </summary>
        public static string Creating3x1Trays {
            get {
                return ResourceManager.GetString("Creating3x1Trays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string CubieBottomPosition {
            get {
                return ResourceManager.GetString("CubieBottomPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string CubieTopPosition {
            get {
                return ResourceManager.GetString("CubieTopPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t decouple because door is not connected.
        /// </summary>
        public static string DecoupleNotOnBus {
            get {
                return ResourceManager.GetString("DecoupleNotOnBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decouple Warning.
        /// </summary>
        public static string DecoupleWarning {
            get {
                return ResourceManager.GetString("DecoupleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t decouple because door is pended or loaded.
        /// </summary>
        public static string DecouplingInventoryWarning {
            get {
                return ResourceManager.GetString("DecouplingInventoryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will decouple the doors.
        /// </summary>
        public static string DecouplingWarningInformation {
            get {
                return ResourceManager.GetString("DecouplingWarningInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defrost Mode.
        /// </summary>
        public static string DefrostMode {
            get {
                return ResourceManager.GetString("DefrostMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please empty the refrigerator of medication items. Refrigerator items will not be accessible from device formulary lists while checked..
        /// </summary>
        public static string DefrostModeWarningMessage {
            get {
                return ResourceManager.GetString("DefrostModeWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected cabinet ?.
        /// </summary>
        public static string DeleteCabinetWarning {
            get {
                return ResourceManager.GetString("DeleteCabinetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected drawer ?.
        /// </summary>
        public static string DeleteDrawerWarning {
            get {
                return ResourceManager.GetString("DeleteDrawerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove a destruction bin that has been assigned inventory..
        /// </summary>
        public static string DestructionBinHasInventory {
            get {
                return ResourceManager.GetString("DestructionBinHasInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispense/Inventory access order*.
        /// </summary>
        public static string DispenseAccessOrder {
            get {
                return ResourceManager.GetString("DispenseAccessOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispense/Inventory access order : 1.
        /// </summary>
        public static string DispenseAccessOrderOne {
            get {
                return ResourceManager.GetString("DispenseAccessOrderOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door 1*.
        /// </summary>
        public static string Door1 {
            get {
                return ResourceManager.GetString("Door1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door 2*.
        /// </summary>
        public static string Door2 {
            get {
                return ResourceManager.GetString("Door2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door 3*.
        /// </summary>
        public static string Door3 {
            get {
                return ResourceManager.GetString("Door3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door 4*.
        /// </summary>
        public static string Door4 {
            get {
                return ResourceManager.GetString("Door4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door at position {0} is not connected.
        /// </summary>
        public static string DoorNotOnBus {
            get {
                return ResourceManager.GetString("DoorNotOnBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors detected.
        /// </summary>
        public static string DoorsDetected {
            get {
                return ResourceManager.GetString("DoorsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors &amp; Pockets:.
        /// </summary>
        public static string DoorsLabel {
            get {
                return ResourceManager.GetString("DoorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Drawers.
        /// </summary>
        public static string DrawerAssignment {
            get {
                return ResourceManager.GetString("DrawerAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer count can not be lower than assigned drawer count.
        /// </summary>
        public static string DrawerCountError {
            get {
                return ResourceManager.GetString("DrawerCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string DrawerNumber0 {
            get {
                return ResourceManager.GetString("DrawerNumber0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DrawerNumber2 {
            get {
                return ResourceManager.GetString("DrawerNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string DrawerNumber6 {
            get {
                return ResourceManager.GetString("DrawerNumber6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer Settings.
        /// </summary>
        public static string DrawerSettings {
            get {
                return ResourceManager.GetString("DrawerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DrawerSettingsDone {
            get {
                return ResourceManager.GetString("DrawerSettingsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawers &amp; Types:.
        /// </summary>
        public static string DrawersLabel {
            get {
                return ResourceManager.GetString("DrawersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawers with invalid configuration:.
        /// </summary>
        public static string DrawersWithInvalidConfiguration {
            get {
                return ResourceManager.GetString("DrawersWithInvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Aux Cabinet Configuration.
        /// </summary>
        public static string EditAuxConfiguration {
            get {
                return ResourceManager.GetString("EditAuxConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Excess Stock.
        /// </summary>
        public static string EditExcess {
            get {
                return ResourceManager.GetString("EditExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit External Return Bin.
        /// </summary>
        public static string EditExtReturnBin {
            get {
                return ResourceManager.GetString("EditExtReturnBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Integrated Main Configuration.
        /// </summary>
        public static string EditIntegratedMainConfig {
            get {
                return ResourceManager.GetString("EditIntegratedMainConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Main Cabinet Configuration.
        /// </summary>
        public static string EditMainConfiguration {
            get {
                return ResourceManager.GetString("EditMainConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Refrigerated Aux.
        /// </summary>
        public static string EditRefrigeratedAux {
            get {
                return ResourceManager.GetString("EditRefrigeratedAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Remote Manager.
        /// </summary>
        public static string EditRemoteManager {
            get {
                return ResourceManager.GetString("EditRemoteManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Remote Stock Configuration.
        /// </summary>
        public static string EditRemoteStockConfiguration {
            get {
                return ResourceManager.GetString("EditRemoteStockConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Smart Remote Manager.
        /// </summary>
        public static string EditSRMConfig {
            get {
                return ResourceManager.GetString("EditSRMConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tower Configuration.
        /// </summary>
        public static string EditTowerConfig {
            get {
                return ResourceManager.GetString("EditTowerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter required drawer information.
        /// </summary>
        public static string EnterRequiredFields {
            get {
                return ResourceManager.GetString("EnterRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess Stock.
        /// </summary>
        public static string ExcessStock {
            get {
                return ResourceManager.GetString("ExcessStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess Stock Name*.
        /// </summary>
        public static string ExcessStockName {
            get {
                return ResourceManager.GetString("ExcessStockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Return Bin.
        /// </summary>
        public static string ExternalBin {
            get {
                return ResourceManager.GetString("ExternalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected drawer has failed.
        /// </summary>
        public static string FailedDrawerWarning {
            get {
                return ResourceManager.GetString("FailedDrawerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more doors are failed, must recover first.
        /// </summary>
        public static string FailedTowerDoorWarning {
            get {
                return ResourceManager.GetString("FailedTowerDoorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From*.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Matrix Full Height ({0}).
        /// </summary>
        public static string FullHeightAccessibleMatrixCount {
            get {
                return ResourceManager.GetString("FullHeightAccessibleMatrixCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUBIE Full Height ({0}).
        /// </summary>
        public static string FullHeightCubieCountFormat {
            get {
                return ResourceManager.GetString("FullHeightCubieCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix Full Height ({0}).
        /// </summary>
        public static string FullHeightMatrixCountFormat {
            get {
                return ResourceManager.GetString("FullHeightMatrixCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Matrix Half Height ({0}).
        /// </summary>
        public static string HalfHeightAccessibleMatrixCount {
            get {
                return ResourceManager.GetString("HalfHeightAccessibleMatrixCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUBIE Half Height ({0}).
        /// </summary>
        public static string HalfHeightCubieCountFormat {
            get {
                return ResourceManager.GetString("HalfHeightCubieCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Internal Return Bin:.
        /// </summary>
        public static string HasInternalReturnBinlbl {
            get {
                return ResourceManager.GetString("HasInternalReturnBinlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Configuration.
        /// </summary>
        public static string IncompleteConfiguration {
            get {
                return ResourceManager.GetString("IncompleteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal bin configured.
        /// </summary>
        public static string InternalBinConfigured {
            get {
                return ResourceManager.GetString("InternalBinConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , drawer .
        /// </summary>
        public static string InternalBinLocationFormat {
            get {
                return ResourceManager.GetString("InternalBinLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal bin not configured.
        /// </summary>
        public static string InternalBinNotConfigured {
            get {
                return ResourceManager.GetString("InternalBinNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Return Bin.
        /// </summary>
        public static string InternalReturnBin {
            get {
                return ResourceManager.GetString("InternalReturnBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Return Bin:.
        /// </summary>
        public static string InterReturnBinLabel {
            get {
                return ResourceManager.GetString("InterReturnBinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Configuration.
        /// </summary>
        public static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this Bin height matrix drawer?.
        /// </summary>
        public static string IsBinHeightMatrixDrawer {
            get {
                return ResourceManager.GetString("IsBinHeightMatrixDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t join a tower that is not on the bus.
        /// </summary>
        public static string JoinNotOnBusError {
            get {
                return ResourceManager.GetString("JoinNotOnBusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t join to a door that is already coupled.
        /// </summary>
        public static string JoinToCoupledDoorsWarning {
            get {
                return ResourceManager.GetString("JoinToCoupledDoorsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Tower.
        /// </summary>
        public static string JoinTower {
            get {
                return ResourceManager.GetString("JoinTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Towers.
        /// </summary>
        public static string JoinTowers {
            get {
                return ResourceManager.GetString("JoinTowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower temperature setting must be more than or equal to {0}.
        /// </summary>
        public static string LowerTemperatureMinError {
            get {
                return ResourceManager.GetString("LowerTemperatureMinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper temperature limit must be greater than the lower temperature limit + 1..
        /// </summary>
        public static string LowerTemperatureUpperTemperatureError {
            get {
                return ResourceManager.GetString("LowerTemperatureUpperTemperatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Drawer Settings to verify the Minitray configuration.
        /// </summary>
        public static string MedCartMiniTrayWarning {
            get {
                return ResourceManager.GetString("MedCartMiniTrayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot select a Cubie that has inventory assigned.
        /// </summary>
        public static string MedsLoadedCubieWarning {
            get {
                return ResourceManager.GetString("MedsLoadedCubieWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot select a mini tray that has inventory assigned.
        /// </summary>
        public static string MedsLoadedMiniWarning {
            get {
                return ResourceManager.GetString("MedsLoadedMiniWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meds are loaded so cannot open the door.
        /// </summary>
        public static string MedsLoadedWarning {
            get {
                return ResourceManager.GetString("MedsLoadedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Meds Warning.
        /// </summary>
        public static string MedsLoadedWarningHeader {
            get {
                return ResourceManager.GetString("MedsLoadedWarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Aux Cabinet.
        /// </summary>
        public static string MiniAuxCabinet {
            get {
                return ResourceManager.GetString("MiniAuxCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini ({0}).
        /// </summary>
        public static string MiniCountFormat {
            get {
                return ResourceManager.GetString("MiniCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameIsRequiredError {
            get {
                return ResourceManager.GetString("NameIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is not unique.
        /// </summary>
        public static string NameNotUniqueError {
            get {
                return ResourceManager.GetString("NameNotUniqueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Cabinet not found. Press Ok to  add Main Cabinet..
        /// </summary>
        public static string NoMainCabinetWaring {
            get {
                return ResourceManager.GetString("NoMainCabinetWaring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No empty slot or replaceable cubie found in any drawer..
        /// </summary>
        public static string NoSlotOrCubieFoundInAnyDrawer {
            get {
                return ResourceManager.GetString("NoSlotOrCubieFoundInAnyDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No empty slot or replaceable cubie found in the open drawer. Please close the drawer..
        /// </summary>
        public static string NoSlotOrCubieFoundInOpenDrawer {
            get {
                return ResourceManager.GetString("NoSlotOrCubieFoundInOpenDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer not assigned to cabinet.
        /// </summary>
        public static string NotAssignedToCabinet {
            get {
                return ResourceManager.GetString("NotAssignedToCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on bus.
        /// </summary>
        public static string NotOnBus {
            get {
                return ResourceManager.GetString("NotOnBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Drawers*.
        /// </summary>
        public static string NumberOfDrawers {
            get {
                return ResourceManager.GetString("NumberOfDrawers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of drawers is required.
        /// </summary>
        public static string NumberofDrawersRequired {
            get {
                return ResourceManager.GetString("NumberofDrawersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pockets*.
        /// </summary>
        public static string NumberOfPockets {
            get {
                return ResourceManager.GetString("NumberOfPockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pockets:.
        /// </summary>
        public static string NumberofPocketslbl {
            get {
                return ResourceManager.GetString("NumberofPocketslbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pockets:.
        /// </summary>
        public static string NumOfPocketsTitle {
            get {
                return ResourceManager.GetString("NumOfPocketsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Door.
        /// </summary>
        public static string OpenDoor {
            get {
                return ResourceManager.GetString("OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the door.
        /// </summary>
        public static string OpenDoorFailureError {
            get {
                return ResourceManager.GetString("OpenDoorFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Door.
        /// </summary>
        public static string OpenDoorFailureErrorHeader {
            get {
                return ResourceManager.GetString("OpenDoorFailureErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the door.
        /// </summary>
        public static string OpenDoorOnExitWarning {
            get {
                return ResourceManager.GetString("OpenDoorOnExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the door before opening another door.
        /// </summary>
        public static string OpenDoorWarning {
            get {
                return ResourceManager.GetString("OpenDoorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Door Warning.
        /// </summary>
        public static string OpenDoorWarningHeader {
            get {
                return ResourceManager.GetString("OpenDoorWarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a drawer that has been assigned inventory.
        /// </summary>
        public static string OpenDrawerWithInventory {
            get {
                return ResourceManager.GetString("OpenDrawerWithInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Door.
        /// </summary>
        public static string OpeningDoor {
            get {
                return ResourceManager.GetString("OpeningDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Tray.
        /// </summary>
        public static string OpeningTray {
            get {
                return ResourceManager.GetString("OpeningTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Open Shelf Pockets*.
        /// </summary>
        public static string OpenShelfPockets {
            get {
                return ResourceManager.GetString("OpenShelfPockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shelf Pockets ({0}).
        /// </summary>
        public static string OpenShelfPocketsCountFormat {
            get {
                return ResourceManager.GetString("OpenShelfPocketsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Open Shelf Pockets:.
        /// </summary>
        public static string OpenShelfPocketsLabel {
            get {
                return ResourceManager.GetString("OpenShelfPocketsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Range Warning Delay*.
        /// </summary>
        public static string OutOfRangeWarningDelay {
            get {
                return ResourceManager.GetString("OutOfRangeWarningDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defrost Mode/Out of Service.
        /// </summary>
        public static string OutOfServiceMode {
            get {
                return ResourceManager.GetString("OutOfServiceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please empty the Refrigerator Cabinet of medication items. Refrigerator Cabinet items will not be accessible from device formulary lists while checked..
        /// </summary>
        public static string OutOfServiceModeWarningMessage {
            get {
                return ResourceManager.GetString("OutOfServiceModeWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please empty the Refrigerator Cabinet of medication items. Refrigerator Cabinet items will not be accessible from device formulary lists while checked..
        /// </summary>
        public static string OutOfServiceWarning {
            get {
                return ResourceManager.GetString("OutOfServiceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pended.
        /// </summary>
        public static string Pended {
            get {
                return ResourceManager.GetString("Pended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the configuration first.
        /// </summary>
        public static string PendingConfigurationWrite {
            get {
                return ResourceManager.GetString("PendingConfigurationWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the cubie release.
        /// </summary>
        public static string PendingCubieReleaseWarning {
            get {
                return ResourceManager.GetString("PendingCubieReleaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door {0}: Number of pockets cannot be lower than number of pockets with inventory.
        /// </summary>
        public static string PocketCountDoorError {
            get {
                return ResourceManager.GetString("PocketCountDoorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door {0}: Number of pockets cannot be lower than number of pockets with inventory ({1}).
        /// </summary>
        public static string PocketCountDoorError2 {
            get {
                return ResourceManager.GetString("PocketCountDoorError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pockets cannot be lower than number of pockets with inventory.
        /// </summary>
        public static string PocketCountError {
            get {
                return ResourceManager.GetString("PocketCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pockets count cannot be less than number of Loaded pockets: {0}.
        /// </summary>
        public static string PocketCountLessThanLoadedFormat {
            get {
                return ResourceManager.GetString("PocketCountLessThanLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pockets can not be less than 1.
        /// </summary>
        public static string PocketCountLessThanOneError {
            get {
                return ResourceManager.GetString("PocketCountLessThanOneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pockets cannot be blank.
        /// </summary>
        public static string PocketsBlank {
            get {
                return ResourceManager.GetString("PocketsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pockets cannot be greater than {0}.
        /// </summary>
        public static string PocketsCountGreaterThanFormat {
            get {
                return ResourceManager.GetString("PocketsCountGreaterThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pockets cannot be less than {0}.
        /// </summary>
        public static string PocketsCountLessThanFormat {
            get {
                return ResourceManager.GetString("PocketsCountLessThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pockets:.
        /// </summary>
        public static string PocketsLabel {
            get {
                return ResourceManager.GetString("PocketsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pockets*.
        /// </summary>
        public static string PocketsWithStar {
            get {
                return ResourceManager.GetString("PocketsWithStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position cannot be greater than 200.
        /// </summary>
        public static string PositionGreaterError {
            get {
                return ResourceManager.GetString("PositionGreaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position cannot be less than 1.
        /// </summary>
        public static string PositionLessThanOneError {
            get {
                return ResourceManager.GetString("PositionLessThanOneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is not unique.
        /// </summary>
        public static string PositionNotUniqueError {
            get {
                return ResourceManager.GetString("PositionNotUniqueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position can not be zero.
        /// </summary>
        public static string PositionZeroError {
            get {
                return ResourceManager.GetString("PositionZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Primary).
        /// </summary>
        public static string PrimaryTower {
            get {
                return ResourceManager.GetString("PrimaryTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name:.
        /// </summary>
        public static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}°C.
        /// </summary>
        public static string RefrigeratorCabinetOutRangeTempCelsius {
            get {
                return ResourceManager.GetString("RefrigeratorCabinetOutRangeTempCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}°F.
        /// </summary>
        public static string RefrigeratorCabinetOutRangeTempFahrenheit {
            get {
                return ResourceManager.GetString("RefrigeratorCabinetOutRangeTempFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} (Normal: {2} - {3}).
        /// </summary>
        public static string RefrigeratorCabinetOutRangeTooltip {
            get {
                return ResourceManager.GetString("RefrigeratorCabinetOutRangeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string ReleaseCubie {
            get {
                return ResourceManager.GetString("ReleaseCubie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Stock.
        /// </summary>
        public static string RemoteStock {
            get {
                return ResourceManager.GetString("RemoteStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        public static string RemoteStockName {
            get {
                return ResourceManager.GetString("RemoteStockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace this Refrigerator Cabinet?.
        /// </summary>
        public static string ReplaceRefrigeratorCabinetWarning {
            get {
                return ResourceManager.GetString("ReplaceRefrigeratorCabinetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace this Remote Manager ?.
        /// </summary>
        public static string ReplaceRemoteManagerWarning {
            get {
                return ResourceManager.GetString("ReplaceRemoteManagerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace this SRM cabinet ?.
        /// </summary>
        public static string ReplaceSRMWarning {
            get {
                return ResourceManager.GetString("ReplaceSRMWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towers being replaced must have the same configuration.
        /// </summary>
        public static string ReplaceTowerConfigurationError {
            get {
                return ResourceManager.GetString("ReplaceTowerConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace this Tower cabinet ?.
        /// </summary>
        public static string ReplaceTowerWarning {
            get {
                return ResourceManager.GetString("ReplaceTowerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing failed Refrigerator Cabinet.
        /// </summary>
        public static string ReplacingFailedRefrigeratorCabinet {
            get {
                return ResourceManager.GetString("ReplacingFailedRefrigeratorCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing failed Remote Manager.
        /// </summary>
        public static string ReplacingFailedRemoteManager {
            get {
                return ResourceManager.GetString("ReplacingFailedRemoteManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing failed SRM.
        /// </summary>
        public static string ReplacingFailedSRM {
            get {
                return ResourceManager.GetString("ReplacingFailedSRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing failed Tower.
        /// </summary>
        public static string ReplacingFailedTower {
            get {
                return ResourceManager.GetString("ReplacingFailedTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report interval must be less than or equal to {0}.
        /// </summary>
        public static string ReportingIntervalMaxError {
            get {
                return ResourceManager.GetString("ReportingIntervalMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report interval must be more than or equal to {0}.
        /// </summary>
        public static string ReportingIntervalMinError {
            get {
                return ResourceManager.GetString("ReportingIntervalMinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Interval*.
        /// </summary>
        public static string ReportInterval {
            get {
                return ResourceManager.GetString("ReportInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reposition.
        /// </summary>
        public static string Reposition {
            get {
                return ResourceManager.GetString("Reposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositioned.
        /// </summary>
        public static string Repositioned {
            get {
                return ResourceManager.GetString("Repositioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping will revert all reposition changes made..
        /// </summary>
        public static string RepositionStopWarning {
            get {
                return ResourceManager.GetString("RepositionStopWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a return bin assigned to this cabinet..
        /// </summary>
        public static string ReturnBinAlreadyAssigned {
            get {
                return ResourceManager.GetString("ReturnBinAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove a return bin that has been assigned inventory..
        /// </summary>
        public static string ReturnBinHasInventory {
            get {
                return ResourceManager.GetString("ReturnBinHasInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Secondary).
        /// </summary>
        public static string SecondaryTower {
            get {
                return ResourceManager.GetString("SecondaryTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Bins ({0}).
        /// </summary>
        public static string SecureBinsCountFormat {
            get {
                return ResourceManager.GetString("SecureBinsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Bins.
        /// </summary>
        public static string SecureBinsLabel {
            get {
                return ResourceManager.GetString("SecureBinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Secure Pockets.
        /// </summary>
        public static string SecurePockets {
            get {
                return ResourceManager.GetString("SecurePockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Secure Pockets:.
        /// </summary>
        public static string SecurePocketsLabel {
            get {
                return ResourceManager.GetString("SecurePocketsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch the drawer position in the cabinet.
        /// </summary>
        public static string SelectDrawerPosition {
            get {
                return ResourceManager.GetString("SelectDrawerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  drawer position.
        /// </summary>
        public static string SelectDrawerPostionTitle {
            get {
                return ResourceManager.GetString("SelectDrawerPostionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select trays to change pocket count.
        /// </summary>
        public static string SelectTraystoChangePocketCount {
            get {
                return ResourceManager.GetString("SelectTraystoChangePocketCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate Tower.
        /// </summary>
        public static string SeparateTower {
            get {
                return ResourceManager.GetString("SeparateTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separating Towers.
        /// </summary>
        public static string SeparatingTowers {
            get {
                return ResourceManager.GetString("SeparatingTowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number:.
        /// </summary>
        public static string SerialNumberLabel {
            get {
                return ResourceManager.GetString("SerialNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer settings have been saved.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}°C.
        /// </summary>
        public static string SRMOutRangeTempCelsius {
            get {
                return ResourceManager.GetString("SRMOutRangeTempCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}°F.
        /// </summary>
        public static string SRMOutRangeTempFahrenheit {
            get {
                return ResourceManager.GetString("SRMOutRangeTempFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} (Normal: {2} - {3}).
        /// </summary>
        public static string SRMOutRangeTooltip {
            get {
                return ResourceManager.GetString("SRMOutRangeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press start to start drawer assignment.
        /// </summary>
        public static string StartDrawerAssingment {
            get {
                return ResourceManager.GetString("StartDrawerAssingment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Space Configuration.
        /// </summary>
        public static string StorageSpaceConfig {
            get {
                return ResourceManager.GetString("StorageSpaceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Range:.
        /// </summary>
        public static string TemperatureRange {
            get {
                return ResourceManager.GetString("TemperatureRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To*.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door is not connected or is coupled.
        /// </summary>
        public static string TowerDoorNotOnBus {
            get {
                return ResourceManager.GetString("TowerDoorNotOnBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t separate towers if any one of them are loaded.
        /// </summary>
        public static string TowerHasInventory {
            get {
                return ResourceManager.GetString("TowerHasInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will cause both towers to become unconfigured and return you to the storage space configuration list..
        /// </summary>
        public static string TowerSeparationWarning {
            get {
                return ResourceManager.GetString("TowerSeparationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A loaded or pended tower can&apos;t be joined with another one.
        /// </summary>
        public static string TowerWithInventoryNotJoinable {
            get {
                return ResourceManager.GetString("TowerWithInventoryNotJoinable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfigured.
        /// </summary>
        public static string Unconfigured {
            get {
                return ResourceManager.GetString("Unconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper temperature setting must be less than or equal to {0}.
        /// </summary>
        public static string UpperTemperatureMaxError {
            get {
                return ResourceManager.GetString("UpperTemperatureMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Range Warning delay must be less than or equal to {0}.
        /// </summary>
        public static string WarningDelayMaxError {
            get {
                return ResourceManager.GetString("WarningDelayMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Range Warning delay must be more than or equal to {0}.
        /// </summary>
        public static string WarningDelayMinimumError {
            get {
                return ResourceManager.GetString("WarningDelayMinimumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
