//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareFusion.Dispensing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareFusion.Dispensing.Resources.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An access failure was detected by the underlying data source. The operation was aborted..
        /// </summary>
        public static string AccessFailedDataSourceException {
            get {
                return ResourceManager.GetString("AccessFailedDataSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing record was changed by another user or system since the last read..
        /// </summary>
        public static string ConcurrencyException {
            get {
                return ResourceManager.GetString("ConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported boolean operator..
        /// </summary>
        public static string Condition_InvalidBooleanOperatorFormat {
            get {
                return ResourceManager.GetString("Condition_InvalidBooleanOperatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported unique identifier operator..
        /// </summary>
        public static string Condition_InvalidGuidOperatorFormat {
            get {
                return ResourceManager.GetString("Condition_InvalidGuidOperatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported string operator..
        /// </summary>
        public static string Condition_InvalidStringOperatorFormat {
            get {
                return ResourceManager.GetString("Condition_InvalidStringOperatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string &apos;{0}&apos; was not found in the configuration file..
        /// </summary>
        public static string DatabaseConnectionString_NotFound {
            get {
                return ResourceManager.GetString("DatabaseConnectionString_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error has ocurred on the underlying data source.  This could be caused by a network connection problem or a hardware issue..
        /// </summary>
        public static string DataSourceException {
            get {
                return ResourceManager.GetString("DataSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deadlock was detected by the underlying data source. The operation was aborted..
        /// </summary>
        public static string DeadlockDataSourceException {
            get {
                return ResourceManager.GetString("DeadlockDataSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load dispensing system settings. There are no settings configured..
        /// </summary>
        public static string LoadFailed_DispensingSystemNotFound {
            get {
                return ResourceManager.GetString("LoadFailed_DispensingSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load external system with the following key &apos;{0}&apos;. It may have been logically deleted or purged from the data source..
        /// </summary>
        public static string LoadFailed_ExternalSystemNotFound {
            get {
                return ResourceManager.GetString("LoadFailed_ExternalSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load facility with the following key &apos;{0}&apos;. It may have been logically deleted or purged from the data source..
        /// </summary>
        public static string LoadFailed_FacilityNotFound {
            get {
                return ResourceManager.GetString("LoadFailed_FacilityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load item with the following key &apos;{0}&apos;. It may have been logically deleted or purged from the data source..
        /// </summary>
        public static string LoadFailed_ItemNotFound {
            get {
                return ResourceManager.GetString("LoadFailed_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load role with the following key &apos;{0}&apos;. It may have been logically deleted or purged from the data source..
        /// </summary>
        public static string LoadFailed_RoleNotFound {
            get {
                return ResourceManager.GetString("LoadFailed_RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load unit with the following key &apos;{0}&apos;. It may have been logically deleted or purged from the data source..
        /// </summary>
        public static string LoadFailed_UnitNotFound {
            get {
                return ResourceManager.GetString("LoadFailed_UnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load user account with the following username &apos;{0}&apos;. It may have been logically deleted or purged from the data source..
        /// </summary>
        public static string LoadFailed_UserAccountByIdentityNotFound {
            get {
                return ResourceManager.GetString("LoadFailed_UserAccountByIdentityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load user account with the following key &apos;{0}&apos;. It may have been logically deleted or purged from the data source..
        /// </summary>
        public static string LoadFailed_UserAccountNotFound {
            get {
                return ResourceManager.GetString("LoadFailed_UserAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout was detected by the underlying data source. The operation was aborted..
        /// </summary>
        public static string TimeoutDataSourceException {
            get {
                return ResourceManager.GetString("TimeoutDataSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected data constraint violation occurred.  &apos;{0}&apos;.
        /// </summary>
        public static string UnhandledConstraintException {
            get {
                return ResourceManager.GetString("UnhandledConstraintException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected data error occurred. &apos;{0}&apos;.
        /// </summary>
        public static string UnhandledDataExceptionFormat {
            get {
                return ResourceManager.GetString("UnhandledDataExceptionFormat", resourceCulture);
            }
        }
    }
}
